from __future__ import annotations

import importlib.util
import json
from pathlib import Path
import subprocess
import sys

import pytest

from openseespy_studio.crack_results import (
    mefi_crack_panel_states,
    mefi_crack_summary,
)
from openseespy_studio.generator import material_to_openseespy, to_openseespy
from openseespy_studio.importer import import_openseespy_source
from openseespy_studio.model import StructuralModel
from openseespy_studio.moment_curvature import (
    MomentCurvatureSpec,
    build_moment_curvature_project,
)
from openseespy_studio.postprocess import moment_curvature_curve
from openseespy_studio.rc_wall import RCWallSpec, build_rc_wall
from openseespy_studio.project import (
    MATERIAL_DEFAULTS,
    AnalysisSettingsData,
    ConnectionData,
    ElementLoadData,
    FiberData,
    LoadPatternData,
    MaterialData,
    NDMaterialData,
    NodalLoadData,
    ProjectDatabase,
    RecorderData,
    SectionData,
    ShellLayerData,
    SolutionResultData,
    TimeSeriesData,
    TransformationData,
)
from openseespy_studio.solver_worker import run_script
from openseespy_studio.ui.viewport import ModelViewport


pytestmark = pytest.mark.integration

if importlib.util.find_spec("openseespy") is None:
    pytest.skip(
        "OpenSeesPy runtime is not installed in the unit-test environment.",
        allow_module_level=True,
    )


def test_asd_embedded_node_element_exists_in_real_opensees():
    import openseespy.opensees as ops

    ops.wipe()
    ops.model("basic", "-ndm", 2, "-ndf", 3)
    ops.node(1, 0.0, 0.0)
    ops.node(2, 1.0, 0.0)
    ops.node(3, 0.0, 1.0)
    ops.node(4, 0.25, 0.25)
    ops.element(
        "ASDEmbeddedNodeElement",
        1,
        4,
        1,
        2,
        3,
        "-rot",
        "-K",
        3.0e10,
    )

    assert 1 in ops.getEleTags()
    ops.wipe()


def test_fully_discrete_rc_wall_builds_in_real_opensees(
    tmp_path: Path,
):
    project = ProjectDatabase()
    project.units = {"length": "m", "force": "N", "time": "s"}
    wall = build_rc_wall(
        project,
        RCWallSpec(
            width=1.22,
            height=2.20,
            thickness=0.1524,
            boundary_width=0.2286,
            vertical_elements=3,
            macro_fibers=6,
            boundary_unconfined_thickness=0.0508,
            boundary_confined_thickness=0.1016,
            reinforcement_mode="fully_discrete",
            boundary_bar_count=4,
            boundary_cover=0.03,
            boundary_layer_mode="front_back",
            web_horizontal_layer_mode="front_back",
            web_vertical_spacing=0.25,
            web_vertical_edge_offset=0.05,
            web_vertical_layer_mode="front_back",
        ),
    )

    script = to_openseespy(
        project.model,
        materials=project.materials,
        sections=project.sections,
        transformations=project.transformations,
        constraints=project.constraints,
        connections=project.connections,
        nd_materials=project.nd_materials,
        units=project.units,
    )
    assert "# ERROR:" not in script
    assert "ASDEmbeddedNodeElement" in script
    assert "corotTruss" in script
    assert wall.horizontal_embedded_coupling_element_tags
    assert wall.web_vertical_element_tags

    script_path = tmp_path / "rc-wall-fully-discrete.py"
    script_path.write_text(script, encoding="utf-8")
    completed = subprocess.run(
        [sys.executable, str(script_path)],
        cwd=tmp_path,
        text=True,
        capture_output=True,
        check=False,
        timeout=30,
    )

    assert completed.returncode == 0, completed.stderr
    assert "Model generated by OpenSeesPy Studio MVP" in completed.stdout


def test_generated_static_cantilever_runs_in_real_opensees(tmp_path: Path):
    model = StructuralModel("real-opensees-smoke")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 0.0, 0.0, 3.0)
    model.set_fixity(1, (1, 1, 1, 1, 1, 1))
    model.add_element(
        1,
        1,
        2,
        section_tag=1,
        transf_tag=1,
    )

    sections = {
        1: SectionData(
            1,
            "Elastic column",
            "Elastic",
            parameters={
                "E": 200.0e9,
                "A": 0.02,
                "Iz": 8.0e-5,
                "Iy": 8.0e-5,
                "G": 80.0e9,
                "J": 1.0e-4,
            },
        )
    }
    transformations = {
        1: TransformationData(
            1,
            "Column",
            "Linear",
            (1.0, 0.0, 0.0),
        )
    }
    time_series = {
        1: TimeSeriesData(1, "Linear", "Linear", factor=1.0)
    }
    load_patterns = {
        1: LoadPatternData(
            1,
            "Lateral",
            "Plain",
            time_series_tag=1,
        )
    }
    nodal_loads = {
        1: NodalLoadData(
            1,
            "Top lateral",
            pattern_tag=1,
            node_tag=2,
            values=(1000.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "Static smoke",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-12,
        max_iterations=20,
        algorithm="Newton",
        steps=1,
        load_increment=1.0,
        control_node=2,
        control_dof=1,
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    script = to_openseespy(
        model,
        sections=sections,
        transformations=transformations,
        time_series=time_series,
        load_patterns=load_patterns,
        nodal_loads=nodal_loads,
        analyses={1: analysis},
        active_analysis_tag=1,
        units={"length": "m", "force": "N", "time": "s"},
    )
    assert "# ERROR:" not in script

    script_path = tmp_path / "cantilever.py"
    result_path = tmp_path / "cantilever-result.json"
    script_path.write_text(script, encoding="utf-8")

    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0
    assert payload["status"] == "completed"
    results = payload["results"]
    assert results["analysis"]["type"] == "Static"
    assert results["convergence"]["steps"][0]["status"] in {
        "converged",
        "recovered",
    }

    displacement = results["final"]["node_displacements"]["2"][0]
    expected = 1000.0 * 3.0**3 / (
        3.0 * 200.0e9 * 8.0e-5
    )
    assert displacement == pytest.approx(expected, rel=1.0e-6)

    reaction = results["final"]["node_reactions"]["1"][0]
    assert reaction == pytest.approx(-1000.0, rel=1.0e-8)

    # The exported source must also run as an ordinary Python script,
    # without the Studio worker or any openseespy_studio import.
    assert "import openseespy_studio" not in script
    standalone = subprocess.run(
        [sys.executable, str(script_path)],
        cwd=tmp_path,
        text=True,
        capture_output=True,
        check=False,
        timeout=30,
    )
    assert standalone.returncode == 0, standalone.stderr
    assert "Model generated by OpenSeesPy Studio" in standalone.stdout



def test_rc_wall_mefi_panel_strain_is_captured_in_real_opensees(
    tmp_path: Path,
):
    project = ProjectDatabase()
    project.units = {"length": "m", "force": "N", "time": "s"}
    wall = build_rc_wall(
        project,
        RCWallSpec(
            width=1.0,
            height=1.5,
            thickness=0.15,
            boundary_width=0.20,
            vertical_elements=1,
            macro_fibers=4,
            boundary_unconfined_thickness=0.05,
            boundary_confined_thickness=0.10,
        ),
    )

    series = {
        1: TimeSeriesData(1, "Lateral", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(
            1,
            "Lateral",
            "Plain",
            time_series_tag=1,
        )
    }
    loads = {
        1: NodalLoadData(
            1,
            "Top lateral",
            pattern_tag=1,
            node_tag=wall.top_node_tags[1],
            values=(1000.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "RC wall crack instrumentation",
        analysis_type="Static",
        constraints_handler="Transformation",
        numberer="RCM",
        system="UmfPack",
        test="NormDispIncr",
        tolerance=1.0e-8,
        max_iterations=50,
        algorithm="Newton",
        integrator="LoadControl",
        steps=1,
        load_increment=1.0,
        control_node=wall.top_node_tags[1],
        control_dof=1,
        recovery=True,
        adaptive_step=False,
        live_convergence=False,
    )

    script = to_openseespy(
        project.model,
        materials=project.materials,
        sections=project.sections,
        transformations=project.transformations,
        constraints=project.constraints,
        connections=project.connections,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
        analyses={1: analysis},
        active_analysis_tag=1,
        nd_materials=project.nd_materials,
        units=project.units,
    )
    assert "'RCPanel'" in script
    assert "'panel_strain'" in script

    script_path = tmp_path / "rc-wall-crack.py"
    result_path = tmp_path / "rc-wall-crack-result.json"
    script_path.write_text(script, encoding="utf-8")
    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"
    results = payload["results"]
    first_element = str(wall.element_tags[0])
    assert first_element in results["mefi_crack_specs"]
    panels = results["history"]["mefi_panel_strains"][first_element]
    assert set(panels) == {"1", "2", "3", "4"}
    assert all(len(rows) == 1 for rows in panels.values())
    assert all(len(rows[0]) == 3 for rows in panels.values())



def _elastic_cantilever(*, mass: float = 0.0):
    model = StructuralModel("real-opensees-workflow")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 0.0, 0.0, 3.0)
    model.set_fixity(1, (1, 1, 1, 1, 1, 1))
    if mass > 0.0:
        model.set_mass(
            2,
            (mass, mass, mass, 0.0, 0.0, 0.0),
        )
    model.add_element(
        1,
        1,
        2,
        section_tag=1,
        transf_tag=1,
    )
    sections = {
        1: SectionData(
            1,
            "Elastic column",
            "Elastic",
            parameters={
                "E": 200.0e9,
                "A": 0.02,
                "Iz": 8.0e-5,
                "Iy": 8.0e-5,
                "G": 80.0e9,
                "J": 1.0e-4,
            },
        )
    }
    transformations = {
        1: TransformationData(
            1,
            "Column",
            "Linear",
            (1.0, 0.0, 0.0),
        )
    }
    return model, sections, transformations


def _run_real_generated(
    tmp_path: Path,
    name: str,
    *,
    model: StructuralModel,
    sections: dict[int, SectionData],
    transformations: dict[int, TransformationData],
    analysis: AnalysisSettingsData,
    materials: dict[int, MaterialData] | None = None,
    connections: dict[int, ConnectionData] | None = None,
    time_series: dict[int, TimeSeriesData] | None = None,
    load_patterns: dict[int, LoadPatternData] | None = None,
    nodal_loads: dict[int, NodalLoadData] | None = None,
):
    script = to_openseespy(
        model,
        materials=materials,
        sections=sections,
        transformations=transformations,
        connections=connections,
        time_series=time_series,
        load_patterns=load_patterns,
        nodal_loads=nodal_loads,
        analyses={analysis.tag: analysis},
        active_analysis_tag=analysis.tag,
        units={"length": "m", "force": "N", "time": "s"},
    )
    assert "# ERROR:" not in script
    assert "import openseespy_studio" not in script
    compile(script, f"<{name}>", "exec")

    script_path = tmp_path / f"{name}.py"
    result_path = tmp_path / f"{name}-result.json"
    script_path.write_text(script, encoding="utf-8")
    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"
    return payload["results"]


def test_frp_confined_concrete_material_constructs_in_real_opensees(
    tmp_path: Path,
):
    material = MaterialData(
        77,
        "FRP confined concrete",
        "FRPConfinedConcrete",
        parameters={
            "fpc1": 27.5e6,
            "fpc2": 27.5e6,
            "epsc0": 0.002,
            "D": 0.400,
            "c": 0.035,
            "Ej": 266.0e9,
            "Sj": 0.0,
            "tj": 0.000222,
            "eju": 0.0163,
            "S": 0.150,
            "fyl": 374.0e6,
            "fyh": 363.0e6,
            "dlong": 0.016,
            "dtrans": 0.006,
            "Es": 200.0e9,
            "nu0": 0.2,
            "k": 0.8,
            "useBuck": 1.0,
        },
    )
    material_line = material_to_openseespy(
        material,
        {"length": "mm", "force": "N", "time": "s"},
    )
    script = "\n".join([
        "import openseespy.opensees as ops",
        "ops.wipe()",
        "ops.model('basic', '-ndm', 1, '-ndf', 1)",
        material_line,
        "ops.node(1, 0.0)",
        "ops.node(2, 1.0)",
        "ops.fix(1, 1)",
        "ops.element('truss', 1, 1, 2, 1.0, 77)",
        "print('FRP_MATERIAL_OK')",
    ])
    script_path = tmp_path / "frp-material-smoke.py"
    script_path.write_text(script, encoding="utf-8")
    completed = subprocess.run(
        [sys.executable, str(script_path)],
        cwd=tmp_path,
        text=True,
        capture_output=True,
        check=False,
        timeout=30,
    )
    if (
        completed.returncode != 0
        and "temporarily removed from the compiled versions"
        in completed.stderr
    ):
        pytest.xfail(
            "Stock OpenSeesPy runtime omits legacy FRPConfinedConcrete."
        )
    assert completed.returncode == 0, completed.stderr
    assert "FRP_MATERIAL_OK" in completed.stdout


def test_imported_wfsection2d_conversion_runs_in_real_opensees(
    tmp_path: Path,
):
    source = r"""
from openseespy.opensees import *
wipe()
model('basic', '-ndm', 2, '-ndf', 3)
uniaxialMaterial(
    'Steel02', 1, 60.0, 29000.0, 0.10,
    18.0, 0.925, 0.15, 0.05, 1.0, 0.05, 1.0, 0.0
)
section('WFSection2d', 1, 1, 10.5, 0.26, 5.77, 0.44, 15, 16)
node(1, 0.0, 0.0)
node(2, 0.0, 120.0)
fix(1, 1, 1, 1)
geomTransf('PDelta', 1)
beamIntegration('Lobatto', 1, 1, 4)
element('forceBeamColumn', 1, 1, 2, 1, 1)
timeSeries('Linear', 1)
pattern('Plain', 1, 1)
load(2, 1.0, 0.0, 0.0)
system('BandGeneral')
numberer('Plain')
constraints('Plain')
test('NormUnbalance', 1.0e-10, 30)
algorithm('Newton')
integrator('LoadControl', 1.0)
analysis('Static')
analyze(1)
"""
    imported = import_openseespy_source(
        source,
        source_name="wf-real-smoke.py",
        units={"length": "in", "force": "kip", "time": "s"},
    )
    assert imported.error_count == 0
    assert imported.project.sections[1].section_type == "Fiber"
    assert len(imported.project.sections[1].compiled_fibers()) == 47

    project = imported.project
    script = to_openseespy(
        project.model,
        materials=project.materials,
        sections=project.sections,
        transformations=project.transformations,
        constraints=project.constraints,
        connections=project.connections,
        time_series=project.time_series,
        load_patterns=project.load_patterns,
        nodal_loads=project.nodal_loads,
        analyses=project.analyses,
        active_analysis_tag=project.active_analysis_tag,
        recorders=project.recorders,
        units=project.units,
    )
    assert "WFSection2d" not in script
    assert "ops.patch('rect'" in script
    assert "# ERROR:" not in script

    script_path = tmp_path / "wf-converted.py"
    result_path = tmp_path / "wf-converted-result.json"
    script_path.write_text(script, encoding="utf-8")
    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"
    assert payload["results"]["analysis"]["type"] == "Static"
    displacement = payload["results"]["final"]["node_displacements"]["2"][0]
    assert displacement > 0.0


def test_generated_2d_elastic_frame_with_linear_algorithm_runs(
    tmp_path: Path,
):
    model = StructuralModel("real-2d-frame", ndm=2, ndf=3)
    model.add_node(1, 0.0, 0.0)
    model.add_node(2, 0.0, 3.0)
    model.set_fixity(1, (1, 1, 1))
    model.add_element(
        1,
        1,
        2,
        element_type="elasticBeamColumn",
        section_tag=1,
        transf_tag=1,
    )
    sections = {
        1: SectionData(
            1,
            "2D elastic section",
            "Elastic",
            parameters={
                "E": 200.0e9,
                "A": 0.02,
                "Iz": 8.0e-5,
                "Iy": 0.0,
                "G": 0.0,
                "J": 0.0,
            },
        )
    }
    transformations = {
        1: TransformationData(1, "2D Linear", "Linear")
    }
    series = {
        1: TimeSeriesData(1, "Load", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Lateral", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Top load",
            pattern_tag=1,
            node_tag=2,
            values=(1000.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "2D linear static",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        algorithm="Linear",
        integrator="LoadControl",
        steps=1,
        load_increment=1.0,
        control_node=2,
        control_dof=1,
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    script = to_openseespy(
        model,
        sections=sections,
        transformations=transformations,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
        analyses={1: analysis},
        active_analysis_tag=1,
        units={"length": "m", "force": "N", "time": "s"},
    )
    assert "ops.model('basic', '-ndm', 2, '-ndf', 3)" in script
    assert "ops.section('Elastic', 1, 2e+11, 0.02, 8e-05)" in script
    assert "ops.geomTransf('Linear', 1)" in script
    assert (
        "ops.element('elasticBeamColumn', 1, 1, 2, "
        "0.02, 2e+11, 8e-05, 1)"
    ) in script
    assert "_studio_primary_algorithm = 'Linear'" in script
    assert "ops.test(" not in script

    script_path = tmp_path / "frame2d-linear.py"
    result_path = tmp_path / "frame2d-linear-result.json"
    script_path.write_text(script, encoding="utf-8")
    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"
    displacement = payload["results"]["final"]["node_displacements"]["2"][0]
    expected = 1000.0 * 3.0**3 / (
        3.0 * 200.0e9 * 8.0e-5
    )
    assert displacement == pytest.approx(expected, rel=1.0e-6)


def test_modified_newton_initial_runs_in_real_opensees(tmp_path: Path):
    model, sections, transformations = _elastic_cantilever()
    series = {
        1: TimeSeriesData(1, "Load", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Lateral", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Top load",
            pattern_tag=1,
            node_tag=2,
            values=(1000.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        91,
        "ModifiedNewton initial smoke",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-10,
        max_iterations=20,
        algorithm="ModifiedNewton",
        algorithm_initial=True,
        integrator="LoadControl",
        steps=1,
        load_increment=1.0,
        control_node=2,
        control_dof=1,
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    script = to_openseespy(
        model,
        sections=sections,
        transformations=transformations,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
        analyses={91: analysis},
        active_analysis_tag=91,
        units={"length": "m", "force": "N", "time": "s"},
    )
    assert "ops.algorithm('ModifiedNewton', '-initial')" in script

    script_path = tmp_path / "modified-newton-initial.py"
    result_path = tmp_path / "modified-newton-initial-result.json"
    script_path.write_text(script, encoding="utf-8")
    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"
    assert payload["results"]["analysis"]["algorithm_initial"] is True


def test_generated_moment_curvature_runs_in_real_opensees(tmp_path: Path):
    model = StructuralModel("moment-curvature-real", ndm=2, ndf=3)
    model.add_node(1, 0.0, 0.0)
    model.add_node(2, 0.0, 0.0)
    model.set_fixity(1, (1, 1, 1))
    model.set_fixity(2, (0, 1, 0))

    materials = {
        1: MaterialData(
            1,
            "Elastic section material",
            "Elastic",
            parameters={"E": 1000.0},
        )
    }
    sections = {
        1: SectionData(
            1,
            "Moment-curvature fiber section",
            "Fiber",
            fibers=[
                FiberData(-1.0, 0.0, 1.0, 1),
                FiberData(1.0, 0.0, 1.0, 1),
            ],
        )
    }
    connections = {
        1: ConnectionData(
            1,
            "Section test",
            "zeroLengthSection",
            1,
            2,
            section_tag=1,
        )
    }
    series = {
        1: TimeSeriesData(1, "Axial preload", "Constant", factor=1.0),
        2: TimeSeriesData(2, "Unit moment", "Linear", factor=1.0),
    }
    patterns = {
        1: LoadPatternData(1, "Axial preload", "Plain", time_series_tag=1),
        2: LoadPatternData(2, "Moment driver", "Plain", time_series_tag=2),
    }
    loads = {
        1: NodalLoadData(
            1,
            "Axial preload",
            pattern_tag=1,
            node_tag=2,
            values=(-10.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        ),
        2: NodalLoadData(
            2,
            "Unit moment",
            pattern_tag=2,
            node_tag=2,
            values=(0.0, 0.0, 1.0, 0.0, 0.0, 0.0),
        ),
    }
    analysis = AnalysisSettingsData(
        1,
        "Moment-curvature smoke",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormUnbalance",
        tolerance=1.0e-10,
        max_iterations=20,
        algorithm="Newton",
        integrator="DisplacementControl",
        steps=4,
        control_node=2,
        control_dof=3,
        displacement_increment=0.001,
        preload_gravity=True,
        gravity_steps=1,
        deferred_pattern_tags=[2],
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    results = _run_real_generated(
        tmp_path,
        "moment-curvature",
        model=model,
        materials=materials,
        sections=sections,
        transformations={},
        connections=connections,
        analysis=analysis,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
    )

    spec = results["moment_curvature"]
    assert spec["kind"] == "moment-curvature"
    assert spec["element_tag"] == 1
    assert spec["moment_component"] == "Mz"
    assert spec["moment_index"] == 1

    history = results["history"]["moment_curvature"]
    assert len(history["force"]) == 4
    assert len(history["deformation"]) == 4
    curvature = [float(row[1]) for row in history["deformation"]]
    moment = [float(row[1]) for row in history["force"]]
    assert curvature[-1] == pytest.approx(0.004, abs=1.0e-10)
    assert abs(moment[-1]) > 0.0
    assert all(
        abs(curvature[index]) > abs(curvature[index - 1])
        for index in range(1, len(curvature))
    )


def test_generated_modal_runs_in_real_opensees(tmp_path: Path):
    model, sections, transformations = _elastic_cantilever(mass=1000.0)
    analysis = AnalysisSettingsData(
        1,
        "Modal smoke",
        analysis_type="Modal",
        num_modes=1,
        eigen_solver="-fullGenLapack",
        live_convergence=False,
    )

    results = _run_real_generated(
        tmp_path,
        "modal",
        model=model,
        sections=sections,
        transformations=transformations,
        analysis=analysis,
    )

    assert results["analysis"]["type"] == "Modal"
    assert len(results["eigenvalues"]) == 1
    assert float(results["eigenvalues"][0]) > 0.0
    assert "1" in results["modes"]


def test_generated_pushover_runs_in_real_opensees(tmp_path: Path):
    model, sections, transformations = _elastic_cantilever()
    series = {
        1: TimeSeriesData(1, "Push", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Push", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Reference lateral load",
            pattern_tag=1,
            node_tag=2,
            values=(1.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "Pushover smoke",
        analysis_type="Pushover",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-10,
        max_iterations=20,
        algorithm="Newton",
        steps=4,
        control_node=2,
        control_dof=1,
        displacement_increment=0.001,
        deferred_pattern_tags=[1],
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    results = _run_real_generated(
        tmp_path,
        "pushover",
        model=model,
        sections=sections,
        transformations=transformations,
        analysis=analysis,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
    )

    assert results["analysis"]["type"] == "Pushover"
    history = results["history"]["displacement"]
    assert len(history) == 4
    assert history[-1][0] == pytest.approx(0.004, abs=1.0e-10)
    assert abs(results["history"]["base_shear"][-1]) > 0.0


def test_generated_cyclic_runs_in_real_opensees(tmp_path: Path):
    model, sections, transformations = _elastic_cantilever()
    series = {
        1: TimeSeriesData(1, "Cyclic", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Cyclic", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Reference lateral load",
            pattern_tag=1,
            node_tag=2,
            values=(1.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "Cyclic smoke",
        analysis_type="Cyclic",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-10,
        max_iterations=20,
        algorithm="Newton",
        control_node=2,
        control_dof=1,
        cyclic_targets=[0.001, -0.001, 0.0],
        cyclic_increment=0.0005,
        deferred_pattern_tags=[1],
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    results = _run_real_generated(
        tmp_path,
        "cyclic",
        model=model,
        sections=sections,
        transformations=transformations,
        analysis=analysis,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
    )

    assert results["analysis"]["type"] == "Cyclic"
    displacement = [
        float(row[0])
        for row in results["history"]["displacement"]
    ]
    assert max(displacement) == pytest.approx(0.001, abs=1.0e-10)
    assert min(displacement) == pytest.approx(-0.001, abs=1.0e-10)
    assert displacement[-1] == pytest.approx(0.0, abs=1.0e-10)


def test_generated_nlth_runs_in_real_opensees(tmp_path: Path):
    model, sections, transformations = _elastic_cantilever(mass=1000.0)
    series = {
        1: TimeSeriesData(
            1,
            "Small ground motion",
            "Path",
            factor=1.0,
            dt=0.01,
            values=[0.0, 0.05, -0.05, 0.0],
        )
    }
    patterns = {
        1: LoadPatternData(
            1,
            "Ground motion X",
            "UniformExcitation",
            time_series_tag=1,
            direction=1,
            factor=1.0,
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "NLTH smoke",
        analysis_type="Transient",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-10,
        max_iterations=20,
        algorithm="Newton",
        steps=3,
        dt=0.01,
        control_node=2,
        control_dof=1,
        deferred_pattern_tags=[1],
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    results = _run_real_generated(
        tmp_path,
        "nlth",
        model=model,
        sections=sections,
        transformations=transformations,
        analysis=analysis,
        time_series=series,
        load_patterns=patterns,
    )

    assert results["analysis"]["type"] == "Transient"
    assert len(results["history"]["time"]) == 3
    assert results["history"]["time"][-1] == pytest.approx(0.03)
    node_history = results["history"]["nodes"]["2"]
    assert len(node_history["disp"]) == 3
    assert len(node_history["accel"]) == 3


def test_generated_fiber_force_beam_column_and_recorder_run_in_real_opensees(
    tmp_path: Path,
):
    model = StructuralModel("fiber-export-smoke")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 0.0, 0.0, 3.0)
    model.set_fixity(1, (1, 1, 1, 1, 1, 1))
    model.add_element(
        1,
        1,
        2,
        element_type="forceBeamColumn",
        section_tag=1,
        transf_tag=1,
        integration_type="Lobatto",
        integration_points=3,
    )

    materials = {
        1: MaterialData(
            1,
            "Elastic fiber",
            "Elastic",
            parameters={"E": 200.0e9},
        )
    }
    sections = {
        1: SectionData(
            1,
            "Fiber section",
            "Fiber",
            parameters={"GJ": 1.0e6},
            fibers=[
                FiberData(-0.10, -0.10, 0.005, 1),
                FiberData(-0.10, 0.10, 0.005, 1),
                FiberData(0.10, -0.10, 0.005, 1),
                FiberData(0.10, 0.10, 0.005, 1),
            ],
        )
    }
    transformations = {
        1: TransformationData(
            1,
            "Column",
            "Linear",
            (1.0, 0.0, 0.0),
        )
    }
    series = {
        1: TimeSeriesData(1, "Axial", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Axial", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Top axial",
            pattern_tag=1,
            node_tag=2,
            values=(0.0, 0.0, -1000.0, 0.0, 0.0, 0.0),
        )
    }
    recorder_path = tmp_path / "fiber-node-disp.out"
    recorders = {
        1: RecorderData(
            1,
            "Top UZ",
            "Node",
            target_tags=[2],
            response="disp",
            dofs=[3],
            file_name=str(recorder_path),
            include_time=True,
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "Fiber static",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-10,
        max_iterations=20,
        algorithm="Newton",
        steps=1,
        load_increment=1.0,
        control_node=2,
        control_dof=3,
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )
    section_response = SolutionResultData(
        2,
        1,
        "Axial section response",
        "SectionResponse",
        element_scope=[1],
        settings={"section": 1, "component": "P"},
    )

    script = to_openseespy(
        model,
        materials=materials,
        sections=sections,
        transformations=transformations,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
        analyses={1: analysis},
        active_analysis_tag=1,
        recorders=recorders,
        units={"length": "m", "force": "N", "time": "s"},
        solution_results={2: section_response},
    )
    assert "# ERROR:" not in script
    compile(script, "<fiber-export>", "exec")

    script_path = tmp_path / "fiber-export.py"
    result_path = tmp_path / "fiber-export-result.json"
    script_path.write_text(script, encoding="utf-8")
    assert run_script(script_path, result_path) == 0

    payload = json.loads(result_path.read_text(encoding="utf-8"))
    assert payload["status"] == "completed"
    assert payload["results"]["analysis"]["type"] == "Static"
    assert payload["results"]["final"]["node_displacements"]["2"][2] < 0.0
    generic = payload["results"]["history"]["section_responses"]["request:2"]
    assert len(generic["force"]) == 1
    assert len(generic["deformation"]) == 1
    assert abs(float(generic["force"][0][0])) > 0.0
    assert abs(float(generic["deformation"][0][0])) > 0.0
    assert recorder_path.exists()
    assert recorder_path.read_text(encoding="utf-8").strip()


def test_generated_zero_length_spring_runs_in_real_opensees(tmp_path: Path):
    model = StructuralModel("zero-length-export-smoke")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 0.0, 0.0, 0.0)
    model.set_fixity(1, (1, 1, 1, 1, 1, 1))
    model.set_fixity(2, (0, 1, 1, 1, 1, 1))

    materials = {
        1: MaterialData(
            1,
            "Translation spring",
            "Elastic",
            parameters={"E": 1.0e6},
        )
    }
    connections = {
        10: ConnectionData(
            10,
            "Base spring",
            "zeroLength",
            1,
            2,
            materials_by_dof={1: 1},
        )
    }
    series = {
        1: TimeSeriesData(1, "Load", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Load", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Spring load",
            pattern_tag=1,
            node_tag=2,
            values=(1000.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "Spring static",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-12,
        max_iterations=20,
        algorithm="Newton",
        steps=1,
        load_increment=1.0,
        control_node=2,
        control_dof=1,
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    script = to_openseespy(
        model,
        materials=materials,
        connections=connections,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
        analyses={1: analysis},
        active_analysis_tag=1,
        units={"length": "m", "force": "N", "time": "s"},
    )
    assert "# ERROR:" not in script
    compile(script, "<zero-length-export>", "exec")

    script_path = tmp_path / "zero-length-export.py"
    result_path = tmp_path / "zero-length-export-result.json"
    script_path.write_text(script, encoding="utf-8")
    assert run_script(script_path, result_path) == 0

    payload = json.loads(result_path.read_text(encoding="utf-8"))
    assert payload["status"] == "completed"
    displacement = payload["results"]["final"]["node_displacements"]["2"][0]
    assert displacement == pytest.approx(0.001, rel=1.0e-8)


def test_research_material_commands_load_in_real_opensees(tmp_path: Path):
    model = StructuralModel("research-material-export-smoke")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.set_fixity(1, (1, 1, 1, 1, 1, 1))

    materials = {
        1: MaterialData(
            1,
            "Bond",
            "Bond_SP01",
            parameters=MATERIAL_DEFAULTS["Bond_SP01"],
        ),
        2: MaterialData(
            2,
            "FRP jacket",
            "FRPConfinedConcrete02",
            parameters=MATERIAL_DEFAULTS["FRPConfinedConcrete02"],
        ),
        3: MaterialData(
            3,
            "Combined hardening",
            "Hardening",
            parameters=MATERIAL_DEFAULTS["Hardening"],
        ),
        4: MaterialData(
            4,
            "Elastic perfectly plastic",
            "ElasticPP",
            parameters=MATERIAL_DEFAULTS["ElasticPP"],
        ),
        5: MaterialData(
            5,
            "Elastic bilinear",
            "ElasticBilin",
            parameters=MATERIAL_DEFAULTS["ElasticBilin"],
        ),
        6: MaterialData(
            6,
            "Smooth hysteresis",
            "HystereticSmooth",
            parameters=MATERIAL_DEFAULTS["HystereticSmooth"],
        ),
    }

    script = to_openseespy(
        model,
        materials=materials,
        units={"length": "mm", "force": "N", "time": "s"},
    )
    assert "# ERROR:" not in script
    compile(script, "<research-material-export>", "exec")

    script_path = tmp_path / "research-material-export.py"
    result_path = tmp_path / "research-material-export-result.json"
    script_path.write_text(script, encoding="utf-8")
    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"


def test_batched_centerline_mesh_contains_only_line_cells():
    model = StructuralModel("centerline-smoke")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 4.0, 0.0, 0.0)
    model.add_node(3, 4.0, 0.0, 3.0)
    model.add_element(11, 1, 2)
    model.add_element(12, 2, 3)

    mesh = ModelViewport._batched_centerline_mesh(model, [11, 12])

    assert mesh is not None
    assert mesh.n_points == 4
    assert mesh.n_lines == 2
    assert mesh.n_verts == 0
    assert mesh.n_cells == 2
    assert list(mesh.cell_data["element_tag"]) == [11, 12]


def test_generated_truss_runs_and_captures_axial_force_in_real_opensees(
    tmp_path: Path,
):
    model = StructuralModel("truss-real-opensees")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 2.0, 0.0, 0.0)
    model.set_fixity(1, (1, 1, 1, 1, 1, 1))
    model.set_fixity(2, (0, 1, 1, 1, 1, 1))
    model.add_element(
        1,
        1,
        2,
        element_type="truss",
        group="truss",
        truss_area=0.01,
        truss_material_tag=1,
    )

    materials = {
        1: MaterialData(
            1,
            "Elastic truss steel",
            "Elastic",
            parameters={"E": 200.0e9},
        )
    }
    series = {
        1: TimeSeriesData(1, "Axial", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Axial", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Axial tension",
            pattern_tag=1,
            node_tag=2,
            values=(1000.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "Truss static",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-12,
        max_iterations=20,
        algorithm="Newton",
        steps=1,
        load_increment=1.0,
        control_node=2,
        control_dof=1,
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    script = to_openseespy(
        model,
        materials=materials,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
        analyses={1: analysis},
        active_analysis_tag=1,
        units={"length": "m", "force": "N", "time": "s"},
    )
    assert "# ERROR:" not in script
    assert "ops.element('Truss', 1, 1, 2, 0.01, 1)" in script
    assert "'element_axial_forces': _studio_element_axial_forces" in script

    script_path = tmp_path / "truss-static.py"
    result_path = tmp_path / "truss-static-result.json"
    script_path.write_text(script, encoding="utf-8")

    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"

    results = payload["results"]
    displacement = results["final"]["node_displacements"]["2"][0]
    assert displacement == pytest.approx(1.0e-6, rel=1.0e-6)

    axial_force = results["final"]["element_axial_forces"]["1"]
    assert abs(float(axial_force)) == pytest.approx(1000.0, rel=1.0e-8)

    global_force = results["final"]["element_forces"]["1"]
    assert len(global_force) >= 6
    assert max(abs(float(value)) for value in global_force) == pytest.approx(
        1000.0,
        rel=1.0e-8,
    )


def test_generated_2d_2dof_truss_runs_and_reports_axial_force(
    tmp_path: Path,
):
    model = StructuralModel("truss-2d-2dof", ndm=2, ndf=2)
    model.add_node(1, 0.0, 0.0)
    model.add_node(2, 2.0, 0.0)
    model.set_fixity(1, (1, 1))
    model.set_fixity(2, (0, 1))
    model.add_element(
        1,
        1,
        2,
        element_type="truss",
        group="truss",
        truss_area=0.01,
        truss_material_tag=1,
    )

    materials = {
        1: MaterialData(
            1,
            "Elastic truss steel",
            "Elastic",
            parameters={"E": 200.0e9},
        )
    }
    series = {
        1: TimeSeriesData(1, "Axial", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Axial", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Axial tension",
            pattern_tag=1,
            node_tag=2,
            values=(1000.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "2D Truss static",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-12,
        max_iterations=20,
        algorithm="Newton",
        steps=1,
        load_increment=1.0,
        control_node=2,
        control_dof=1,
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    script = to_openseespy(
        model,
        materials=materials,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
        analyses={1: analysis},
        active_analysis_tag=1,
        units={"length": "m", "force": "N", "time": "s"},
    )

    assert "ops.model('basic', '-ndm', 2, '-ndf', 2)" in script
    assert "ops.node(1, 0, 0)" in script
    assert "ops.node(2, 2, 0)" in script
    assert "ops.fix(1, 1, 1)" in script
    assert "ops.fix(2, 0, 1)" in script
    assert "ops.load(2, 1000, 0)" in script
    assert "# ERROR:" not in script

    script_path = tmp_path / "truss-2d.py"
    result_path = tmp_path / "truss-2d-result.json"
    script_path.write_text(script, encoding="utf-8")

    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"
    results = payload["results"]
    assert results["final"]["node_displacements"]["2"][0] == pytest.approx(
        1.0e-6,
        rel=1.0e-6,
    )
    axial = results["final"]["element_axial_forces"]["1"]
    assert abs(float(axial)) == pytest.approx(1000.0, rel=1.0e-8)



def test_isolated_moment_curvature_workflow_runs_in_real_opensees(
    tmp_path: Path,
):
    source = ProjectDatabase(
        name="MC integration",
        model=StructuralModel("MC integration", ndm=2, ndf=3),
        units={"length": "m", "force": "N", "time": "s"},
    )
    source.add_section(
        SectionData(
            21,
            "Elastic MC section",
            "Elastic",
            parameters={
                "E": 30.0e9,
                "A": 0.16,
                "Iz": 0.002,
                "Iy": 0.0015,
                "G": 12.0e9,
                "J": 0.0004,
            },
        )
    )

    project = build_moment_curvature_project(
        source,
        MomentCurvatureSpec(
            section_tag=21,
            axis="Mz",
            axial_load=0.0,
            max_curvature=0.001,
            increments=10,
        ),
    )
    script = to_openseespy(
        project.model,
        materials=project.materials,
        sections=project.sections,
        transformations=project.transformations,
        constraints=project.constraints,
        connections=project.connections,
        time_series=project.time_series,
        load_patterns=project.load_patterns,
        nodal_loads=project.nodal_loads,
        analyses=project.analyses,
        active_analysis_tag=project.active_analysis_tag,
        element_loads=project.element_loads,
        prescribed_displacements=project.prescribed_displacements,
        recorders=project.recorders,
        units=project.units,
        solution_results=project.solution_results,
    )
    assert "ops.element('zeroLengthSection', 1, 1, 2, 21" in script
    assert "'kind': 'moment-curvature'" in script

    script_path = tmp_path / "moment-curvature.py"
    result_path = tmp_path / "moment-curvature-result.json"
    script_path.write_text(script, encoding="utf-8")
    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"

    curvature, moment, component, element_tag = moment_curvature_curve(
        payload["results"]
    )
    assert component == "Mz"
    assert element_tag == 1
    assert curvature[-1] == pytest.approx(0.001, rel=1.0e-8)
    expected_moment = 30.0e9 * 0.002 * 0.001
    assert moment[-1] == pytest.approx(expected_moment, rel=1.0e-6)


def test_generated_asd_shell_q4_constructs_in_real_opensees(
    tmp_path: Path,
):
    model = StructuralModel("real-shell", ndm=3, ndf=6)
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 2.0, 0.0, 0.0)
    model.add_node(3, 2.0, 1.0, 0.0)
    model.add_node(4, 0.0, 1.0, 0.0)
    model.add_element(
        1,
        1,
        2,
        element_type="ASDShellQ4",
        section_tag=1,
        group="shell",
        k=3,
        l=4,
        shell_corotational=True,
    )
    sections = {
        1: SectionData(
            1,
            "Elastic shell",
            "ElasticMembranePlate",
            parameters={
                "E": 30.0e9,
                "nu": 0.2,
                "h": 0.18,
                "rho": 0.0,
                "EpModifier": 1.0,
            },
        )
    }

    script = to_openseespy(
        model,
        sections=sections,
        units={"length": "m", "force": "N", "time": "s"},
    )
    assert "# ERROR:" not in script
    assert (
        "ops.section('ElasticMembranePlateSection', "
        "1, 3e+10, 0.2, 0.18, 0, 1)"
        in script
    )
    assert (
        "ops.element('ASDShellQ4', 1, 1, 2, 3, 4, 1, '-corotational')"
        in script
    )

    script_path = tmp_path / "shell-q4-smoke.py"
    script_path.write_text(script, encoding="utf-8")
    completed = subprocess.run(
        [sys.executable, str(script_path)],
        cwd=tmp_path,
        text=True,
        capture_output=True,
        check=False,
        timeout=30,
    )

    assert completed.returncode == 0, completed.stderr
    assert "Model generated by OpenSeesPy Studio" in completed.stdout



def test_generated_shell_analysis_captures_force_and_deformation_results(
    tmp_path: Path,
):
    model = StructuralModel("real-shell-results", ndm=3, ndf=6)
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 1.0, 0.0, 0.0)
    model.add_node(3, 1.0, 1.0, 0.0)
    model.add_node(4, 0.0, 1.0, 0.0)
    model.set_fixity(1, (1, 1, 1, 1, 1, 1))
    model.set_fixity(4, (1, 1, 1, 1, 1, 1))
    model.add_element(
        1,
        1,
        2,
        element_type="ASDShellQ4",
        section_tag=1,
        group="shell",
        k=3,
        l=4,
    )

    sections = {
        1: SectionData(
            1,
            "Elastic shell",
            "ElasticMembranePlate",
            parameters={
                "E": 30.0e9,
                "nu": 0.2,
                "h": 0.10,
                "rho": 0.0,
                "EpModifier": 1.0,
            },
        )
    }
    time_series = {
        1: TimeSeriesData(1, "Linear", "Linear", factor=1.0)
    }
    load_patterns = {
        1: LoadPatternData(
            1,
            "Shell tip load",
            "Plain",
            time_series_tag=1,
        )
    }
    nodal_loads = {
        1: NodalLoadData(
            1,
            "Node 2 down",
            pattern_tag=1,
            node_tag=2,
            values=(0.0, 0.0, -1000.0, 0.0, 0.0, 0.0),
        ),
        2: NodalLoadData(
            2,
            "Node 3 down",
            pattern_tag=1,
            node_tag=3,
            values=(0.0, 0.0, -1000.0, 0.0, 0.0, 0.0),
        ),
    }
    analysis = AnalysisSettingsData(
        1,
        "Static shell result smoke",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="RCM",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-10,
        max_iterations=30,
        algorithm="Newton",
        steps=1,
        load_increment=1.0,
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    force_recorder_path = tmp_path / "shell_gp1_force.out"
    deformation_recorder_path = tmp_path / "shell_gp1_deformation.out"
    recorders = {
        1: RecorderData(
            1,
            "Shell GP1 force",
            "Shell",
            target_tags=[1],
            response="force",
            file_name=str(force_recorder_path),
            include_time=True,
            section_number=1,
        ),
        2: RecorderData(
            2,
            "Shell GP1 deformation",
            "Shell",
            target_tags=[1],
            response="deformation",
            file_name=str(deformation_recorder_path),
            include_time=True,
            section_number=1,
        ),
    }

    script = to_openseespy(
        model,
        sections=sections,
        time_series=time_series,
        load_patterns=load_patterns,
        nodal_loads=nodal_loads,
        analyses={1: analysis},
        active_analysis_tag=1,
        recorders=recorders,
        units={"length": "m", "force": "N", "time": "s"},
    )
    assert "# ERROR:" not in script

    script_path = tmp_path / "shell-result-smoke.py"
    result_path = tmp_path / "shell-result-smoke.json"
    script_path.write_text(script, encoding="utf-8")
    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"
    final = payload["results"]["final"]

    force = final["shell_section_forces"]["1"]
    deformation = final["shell_section_deformations"]["1"]
    assert len(force["gauss_points"]) == 4
    assert len(deformation["gauss_points"]) == 4
    assert len(force["average"]) >= 8
    assert len(deformation["average"]) >= 8
    assert any(abs(float(value)) > 0.0 for value in force["average"])
    assert any(
        abs(float(value)) > 0.0
        for value in deformation["average"]
    )

    for recorder_path in (
        force_recorder_path,
        deformation_recorder_path,
    ):
        assert recorder_path.exists()
        rows = [
            line.strip()
            for line in recorder_path.read_text(
                encoding="utf-8"
            ).splitlines()
            if line.strip()
        ]
        assert rows
        values = [float(value) for value in rows[-1].split()]
        # time/load factor + 8 shell section components
        assert len(values) >= 9


def test_generated_shell_surface_pressure_runs_in_real_opensees(
    tmp_path: Path,
):
    model = StructuralModel("real-shell-pressure", ndm=3, ndf=6)
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 1.0, 0.0, 0.0)
    model.add_node(3, 1.0, 1.0, 0.0)
    model.add_node(4, 0.0, 1.0, 0.0)
    model.set_fixity(1, (1, 1, 1, 1, 1, 1))
    model.set_fixity(4, (1, 1, 1, 1, 1, 1))
    model.add_element(
        1,
        1,
        2,
        element_type="ASDShellQ4",
        section_tag=1,
        group="shell",
        k=3,
        l=4,
    )

    sections = {
        1: SectionData(
            1,
            "Elastic shell",
            "ElasticMembranePlate",
            parameters={
                "E": 30.0e9,
                "nu": 0.2,
                "h": 0.10,
                "rho": 0.0,
                "EpModifier": 1.0,
            },
        )
    }
    series = {
        1: TimeSeriesData(1, "Pressure", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(
            1,
            "Pressure",
            "Plain",
            time_series_tag=1,
        )
    }
    pressure = {
        1: ElementLoadData(
            1,
            "Uniform shell pressure",
            1,
            1,
            "SurfacePressure",
            pressure=-1000.0,
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "Shell pressure static",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="RCM",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-10,
        max_iterations=30,
        algorithm="Newton",
        steps=1,
        load_increment=1.0,
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    script = to_openseespy(
        model,
        sections=sections,
        time_series=series,
        load_patterns=patterns,
        element_loads=pressure,
        analyses={1: analysis},
        active_analysis_tag=1,
        units={"length": "m", "force": "N", "time": "s"},
    )
    assert "# ERROR:" not in script
    assert "ops.element('SurfaceLoad', 2, 1, 2, 3, 4, -1000)" in script
    assert "ops.eleLoad('-ele', 2, '-type', '-surfaceLoad')" in script

    script_path = tmp_path / "shell-pressure.py"
    result_path = tmp_path / "shell-pressure-result.json"
    script_path.write_text(script, encoding="utf-8")

    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"
    final = payload["results"]["final"]

    assert float(final["node_displacements"]["2"][2]) < 0.0
    assert float(final["node_displacements"]["3"][2]) < 0.0

    reaction_z = (
        float(final["node_reactions"]["1"][2])
        + float(final["node_reactions"]["4"][2])
    )
    assert reaction_z == pytest.approx(1000.0, rel=1.0e-6)


@pytest.mark.parametrize("section_type", ["PlateFiber", "LayeredShell"])
def test_generated_nonlinear_shell_constructs_in_real_opensees(
    tmp_path: Path,
    section_type: str,
):
    model = StructuralModel(f"real-{section_type}")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 2.0, 0.0, 0.0)
    model.add_node(3, 2.0, 1.0, 0.0)
    model.add_node(4, 0.0, 1.0, 0.0)
    model.add_element(
        1,
        1,
        2,
        element_type="ASDShellQ4",
        section_tag=1,
        group="shell",
        k=3,
        l=4,
    )

    nd_materials = {
        1: NDMaterialData(
            1,
            "Elastic isotropic shell material",
            "ElasticIsotropic",
            parameters={
                "E": 30.0e9,
                "nu": 0.2,
                "rho": 2400.0,
            },
        )
    }
    if section_type == "PlateFiber":
        section = SectionData(
            1,
            "Plate fiber",
            "PlateFiber",
            parameters={"h": 0.15},
            nd_material_tag=1,
        )
    else:
        section = SectionData(
            1,
            "Layered shell",
            "LayeredShell",
            shell_layers=[
                ShellLayerData(1, 0.05),
                ShellLayerData(1, 0.05),
                ShellLayerData(1, 0.05),
            ],
        )

    script = to_openseespy(
        model,
        sections={1: section},
        units={"length": "m", "force": "N", "time": "s"},
        nd_materials=nd_materials,
    )
    assert "# ERROR:" not in script
    assert "ops.nDMaterial('ElasticIsotropic'" in script
    assert f"ops.section('{section_type}'" in script
    assert "ops.element('ASDShellQ4'" in script

    script_path = tmp_path / f"{section_type}-shell.py"
    script_path.write_text(script, encoding="utf-8")
    completed = subprocess.run(
        [sys.executable, str(script_path)],
        cwd=tmp_path,
        text=True,
        capture_output=True,
        check=False,
        timeout=30,
    )
    assert completed.returncode == 0, completed.stderr
    assert "Model generated by OpenSeesPy Studio" in completed.stdout



def test_new_empty_project_draw_polyline_with_real_qt_mouse_events():
    from PySide6.QtCore import QPoint, Qt
    from PySide6.QtTest import QTest
    from PySide6.QtWidgets import QApplication

    from openseespy_studio.ui.main_window import MainWindow

    app = QApplication.instance()
    owns_app = app is None
    if app is None:
        app = QApplication([])

    window = MainWindow()
    try:
        window.show()
        app.processEvents()
        window._new_model()
        app.processEvents()

        assert not window.project.points
        assert not window.project.lines

        action = window.actions["line_geometry_pick"]
        action.trigger()
        app.processEvents()

        assert action.isChecked()
        assert window.viewport.interaction_tool() == "geometry_sketch"
        assert window.viewport._display_domain == "geometry"

        widget = window.viewport.plotter.interactor
        width = max(widget.width(), 300)
        height = max(widget.height(), 300)
        p1 = QPoint(width // 3, height // 2)
        p2 = QPoint(2 * width // 3, height // 2)

        original_mapper = window.viewport.geometry_workplane_point
        window.viewport.geometry_workplane_point = (
            lambda x, y: (float(x), float(y), 0.0)
        )

        QTest.mouseClick(widget, Qt.LeftButton, pos=p1)
        app.processEvents()
        assert window._geometry_line_anchor_snap is not None
        assert len(window.project.points) == 0
        assert len(window.project.lines) == 0

        QTest.mouseClick(widget, Qt.LeftButton, pos=p2)
        app.processEvents()

        assert len(window.project.points) == 2, (
            window.status_message.text(),
            window._geometry_line_anchor_snap,
            window._geometry_line_point_tags,
        )
        assert len(window.project.lines) == 1
        line = next(iter(window.project.lines.values()))
        assert line.point_i != line.point_j
    finally:
        if "original_mapper" in locals():
            window.viewport.geometry_workplane_point = original_mapper
        window._set_dirty(False)
        window.undo_stack.setClean()
        window.close()
        app.processEvents()
        if owns_app:
            app.quit()


def test_empty_project_polyline_direct_payload_commits_segment():
    from PySide6.QtWidgets import QApplication

    from openseespy_studio.ui.main_window import MainWindow

    app = QApplication.instance() or QApplication([])
    window = MainWindow()
    try:
        window._new_model()
        window.actions["line_geometry_pick"].trigger()
        window._handle_geometry_line_sketch_click(
            {
                "world": (-1.0, 0.0, 0.0),
                "screen": (100.0, 100.0),
                "plane": "xy",
            }
        )
        window._handle_geometry_line_sketch_click(
            {
                "world": (1.0, 0.0, 0.0),
                "screen": (300.0, 100.0),
                "plane": "xy",
            }
        )
        assert len(window.project.points) == 2, window.status_message.text()
        assert len(window.project.lines) == 1, window.status_message.text()
    finally:
        window._set_dirty(False)
        window.undo_stack.setClean()
        window.close()
        app.processEvents()



def test_new_empty_project_draw_rectangle_with_real_qt_mouse_events():
    from PySide6.QtCore import QPoint, Qt
    from PySide6.QtTest import QTest
    from PySide6.QtWidgets import QApplication

    from openseespy_studio.ui.main_window import MainWindow

    app = QApplication.instance() or QApplication([])
    window = MainWindow()
    try:
        window._new_model()
        action = window.actions["surface_geometry_pick"]
        action.trigger()
        app.processEvents()

        assert action.isChecked()
        assert window.viewport.interaction_tool() == "geometry_sketch"
        assert window.viewport._display_domain == "geometry"

        original_mapper = window.viewport.geometry_workplane_point
        window.viewport.geometry_workplane_point = (
            lambda x, y: (float(x), float(y), 0.0)
        )

        widget = window.viewport.plotter.interactor
        p1 = QPoint(120, 120)
        p2 = QPoint(320, 260)
        QTest.mouseClick(widget, Qt.LeftButton, pos=p1)
        app.processEvents()
        assert window._geometry_surface_anchor_snap is not None

        QTest.mouseClick(widget, Qt.LeftButton, pos=p2)
        app.processEvents()

        assert len(window.project.points) == 4
        assert len(window.project.surfaces) == 1
        surface = next(iter(window.project.surfaces.values()))
        assert surface.corner_point_tags is not None
        assert len(set(surface.corner_point_tags)) == 4
    finally:
        if "original_mapper" in locals():
            window.viewport.geometry_workplane_point = original_mapper
        window._set_dirty(False)
        window.undo_stack.setClean()
        window.close()
        app.processEvents()


def test_new_empty_project_point_dialog_creates_visible_geometry():
    from unittest.mock import patch

    from PySide6.QtWidgets import QApplication

    from openseespy_studio.project import PointGeometryData
    from openseespy_studio.ui.line_geometry_dialog import PointGeometryDialog
    from openseespy_studio.ui.main_window import MainWindow

    app = QApplication.instance() or QApplication([])
    window = MainWindow()
    try:
        window._new_model()
        point = PointGeometryData(1, "Point 1", (1.0, 2.0, 3.0))
        with (
            patch.object(PointGeometryDialog, "exec", return_value=True),
            patch.object(PointGeometryDialog, "data", return_value=point),
        ):
            tag = window._create_point_geometry()

        assert tag == 1
        assert len(window.project.points) == 1
        assert window.viewport._display_domain == "geometry"
        assert 1 in window.viewport._points
    finally:
        window._set_dirty(False)
        window.undo_stack.setClean()
        window.close()
        app.processEvents()



def test_custom_sketch_plane_rectangle_creates_surface_on_plane():
    from PySide6.QtWidgets import QApplication

    from openseespy_studio.project import SketchPlaneData
    from openseespy_studio.ui.main_window import MainWindow

    app = QApplication.instance() or QApplication([])
    window = MainWindow()
    try:
        window._new_model()
        plane = SketchPlaneData(
            tag=1,
            name="Inclined Roof",
            origin=(0.0, 0.0, 2.0),
            u_axis=(1.0, 0.0, 0.0),
            v_axis=(0.0, 1.0, 1.0),
        )
        window.project.add_sketch_plane(plane)
        window._activate_sketch_plane(1, look_at=False)
        window.actions["geometry_snap"].setChecked(False)
        window.actions["surface_geometry_pick"].trigger()

        first = plane.world_from_uv(0.0, 0.0)
        opposite = plane.world_from_uv(4.0, 3.0)
        window._handle_geometry_rectangle_sketch_click(
            {
                "world": first,
                "screen": (100.0, 100.0),
                "plane": "plane:1",
            }
        )
        window._handle_geometry_rectangle_sketch_click(
            {
                "world": opposite,
                "screen": (400.0, 300.0),
                "plane": "plane:1",
            }
        )

        assert len(window.project.points) == 4
        assert len(window.project.surfaces) == 1
        surface = next(iter(window.project.surfaces.values()))
        assert surface.corner_point_tags is not None
        assert len(set(surface.corner_point_tags)) == 4
        for tag in surface.corner_point_tags:
            point = window.project.points[int(tag)]
            assert abs(plane.signed_distance(point.xyz)) <= 1.0e-9
    finally:
        window._set_dirty(False)
        window.undo_stack.setClean()
        window.close()
        app.processEvents()



def test_origin_oxyz_toggle_tracks_true_global_origin():
    from PySide6.QtWidgets import QApplication

    from openseespy_studio.ui.main_window import MainWindow

    app = QApplication.instance() or QApplication([])
    window = MainWindow()
    try:
        window._new_model()
        actors = window.viewport.plotter.renderer.actors
        assert window.viewport.origin_axes_visible() is True
        assert "origin-axes-o" in actors
        assert "origin-axis-x" in actors
        assert "origin-axis-y" in actors
        assert "origin-axis-z" in actors

        window._toggle_origin_axes(False)
        actors = window.viewport.plotter.renderer.actors
        assert window.viewport.origin_axes_visible() is False
        assert "origin-axis-x" not in actors
        assert "origin-axis-y" not in actors
        assert "origin-axis-z" not in actors

        window._toggle_origin_axes(True)
        actors = window.viewport.plotter.renderer.actors
        assert window.viewport.origin_axes_visible() is True
        assert "origin-axes-o" in actors
        assert "origin-axis-x" in actors
        assert "origin-axis-y" in actors
        assert "origin-axis-z" in actors
    finally:
        window._set_dirty(False)
        window.undo_stack.setClean()
        window.close()
        app.processEvents()



def test_geometry_grid_persists_after_line_and_surface_commit():
    from PySide6.QtWidgets import QApplication

    from openseespy_studio.ui.main_window import MainWindow

    app = QApplication.instance() or QApplication([])
    window = MainWindow()
    try:
        window._new_model()
        window.viewport.set_display_domain("geometry")
        window.viewport.set_geometry_sketch_plane("xy", 0.0)
        window.viewport.set_geometry_sketch_grid_visible(True)

        window.actions["line_geometry_pick"].trigger()
        window._handle_geometry_line_sketch_click(
            {"world": (0.0, 0.0, 0.0), "screen": (0.0, 0.0)}
        )
        window._handle_geometry_line_sketch_click(
            {"world": (2.0, 0.0, 0.0), "screen": (200.0, 0.0)}
        )
        assert "geometry-sketch-grid" in window.viewport.plotter.renderer.actors

        window._activate_geometry_surface_pick_tool(True)
        window._handle_geometry_rectangle_sketch_click(
            {"world": (0.0, 1.0, 0.0), "screen": (0.0, 100.0)}
        )
        window._handle_geometry_rectangle_sketch_click(
            {"world": (2.0, 3.0, 0.0), "screen": (200.0, 300.0)}
        )
        assert "geometry-sketch-grid" in window.viewport.plotter.renderer.actors
        assert window.actions["geometry_grid"].isChecked()
    finally:
        window._set_dirty(False)
        window.undo_stack.setClean()
        window.close()
        app.processEvents()


def test_geometry_measure_accepts_free_plane_locations():
    from PySide6.QtWidgets import QApplication

    from openseespy_studio.ui.main_window import MainWindow

    app = QApplication.instance() or QApplication([])
    window = MainWindow()
    try:
        window._new_model()
        window.viewport.set_display_domain("geometry")
        window.actions["measure_distance"].trigger()

        first = {
            "kind": None,
            "tag": None,
            "world": (0.0, 0.0, 0.0),
            "screen": (0.0, 0.0),
        }
        second = {
            "kind": None,
            "tag": None,
            "world": (3.0, 4.0, 0.0),
            "screen": (300.0, 400.0),
        }
        assert window._handle_measure_click(first) is True
        assert window._measure_first_xyz == (0.0, 0.0, 0.0)
        assert window._handle_measure_click(second) is True
        assert window._measure_first_xyz is None
        assert window.viewport._measurement_counter == 1
        assert any(
            name.startswith("measure-1-")
            for name in window.viewport._measurement_actor_names
        )
    finally:
        window._set_dirty(False)
        window.undo_stack.setClean()
        window.close()
        app.processEvents()


def test_rw_a20_100kn_load_exceeds_mefi_cracking_strain_in_real_opensees(
    tmp_path: Path,
):
    project = ProjectDatabase()
    project.units = {"length": "m", "force": "N", "time": "s"}
    wall = build_rc_wall(project, RCWallSpec())

    series = {
        1: TimeSeriesData(1, "Lateral", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(
            1,
            "Lateral",
            "Plain",
            time_series_tag=1,
        )
    }
    loads = {
        1: NodalLoadData(
            1,
            "Top left lateral",
            pattern_tag=1,
            node_tag=wall.top_node_tags[0],
            values=(50000.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        ),
        2: NodalLoadData(
            2,
            "Top right lateral",
            pattern_tag=1,
            node_tag=wall.top_node_tags[1],
            values=(50000.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        ),
    }
    analysis = AnalysisSettingsData(
        1,
        "RW-A20 100 kN crack check",
        analysis_type="Static",
        constraints_handler="Transformation",
        numberer="RCM",
        system="UmfPack",
        test="NormDispIncr",
        tolerance=1.0e-8,
        max_iterations=100,
        algorithm="Newton",
        integrator="LoadControl",
        steps=100,
        load_increment=0.01,
        control_node=wall.top_node_tags[1],
        control_dof=1,
        recovery=True,
        adaptive_step=False,
        live_convergence=False,
    )

    script = to_openseespy(
        project.model,
        materials=project.materials,
        sections=project.sections,
        transformations=project.transformations,
        constraints=project.constraints,
        connections=project.connections,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
        analyses={1: analysis},
        active_analysis_tag=1,
        nd_materials=project.nd_materials,
        units=project.units,
    )
    script_path = tmp_path / "rw-a20-100kn-crack.py"
    result_path = tmp_path / "rw-a20-100kn-crack-result.json"
    script_path.write_text(script, encoding="utf-8")

    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"
    results = payload["results"]
    specs = results["mefi_crack_specs"]
    final = results["final"]["mefi_panel_strains"]

    ratios = []
    for element_key, spec in specs.items():
        element_rows = final.get(str(element_key), {})
        for index, panel in enumerate(spec.get("panels", []), start=1):
            threshold = panel.get("cracking_strain")
            values = element_rows.get(
                str(int(panel.get("panel", index))),
                [],
            )
            if threshold is None or len(values) < 3:
                continue
            ex, ey, gxy = map(float, values[:3])
            average = 0.5 * (ex + ey)
            radius = (
                (0.5 * (ex - ey)) ** 2
                + (0.5 * gxy) ** 2
            ) ** 0.5
            epsilon_1 = average + radius
            ratios.append(epsilon_1 / float(threshold))

    assert ratios, "No MEFI crack ratios were captured."
    assert max(ratios) >= 1.0, (
        "Expected the 100 kN RW-A20 check to exceed the configured "
        f"cracking strain; max epsilon1/epsilon_cr={max(ratios):.6g}"
    )


def test_imported_rc_wall_produces_crack_history_in_real_opensees(
    tmp_path: Path,
):
    lines = [
        "import openseespy.opensees as ops",
        "ops.model('basic', '-ndm', 2, '-ndf', 3)",
    ]
    height = 2209.8
    width = 1220.0
    levels = 7
    dy = height / levels
    node_tag = 1
    for level in range(levels + 1):
        y = level * dy
        lines.append(f"ops.node({node_tag}, 0.0, {y!r})")
        lines.append(f"ops.node({node_tag + 1}, {width!r}, {y!r})")
        node_tag += 2
    lines.extend([
        "ops.fix(1, 1, 1, 1)",
        "ops.fix(2, 1, 1, 1)",
        "ops.uniaxialMaterial('Steel02', 1, 469.93, 200000.0, 0.02, 20.0, 0.925, 0.15)",
        "ops.uniaxialMaterial('Steel02', 2, 409.71, 200000.0, 0.02, 20.0, 0.925, 0.15)",
        "ops.uniaxialMaterial('Steel02', 3, 429.78, 200000.0, 0.01, 20.0, 0.925, 0.15)",
        "ops.uniaxialMaterial('Concrete02', 4, -47.09, -0.00232, 0.0, -0.037, 0.1, 2.13, 1738.33)",
        "ops.uniaxialMaterial('Concrete02', 5, -53.78, -0.00397, -9.42, -0.047, 0.1, 2.13, 1827.12)",
        "ops.nDMaterial('OrthotropicRAConcrete', 6, 4, 0.00008, -0.00232, 0.0, '-damageCte1', 0.175, '-damageCte2', 0.5)",
        "ops.nDMaterial('OrthotropicRAConcrete', 7, 5, 0.00008, -0.00397, 0.0, '-damageCte1', 0.175, '-damageCte2', 0.5)",
        "ops.nDMaterial('SmearedSteelDoubleLayer', 8, 1, 2, 0.0027, 0.0027, 0.0)",
        "ops.nDMaterial('SmearedSteelDoubleLayer', 9, 1, 3, 0.0082, 0.0323, 0.0)",
        "ops.section('RCLMS', 10, 1, 1, '-reinfSteel', 8, '-conc', 6, '-concThick', 152.4)",
        "ops.section('RCLMS', 11, 1, 2, '-reinfSteel', 9, '-conc', 6, 7, '-concThick', 50.8, 101.6)",
    ])
    widths = [
        228.6,
        127.1333333333,
        127.1333333333,
        127.1333333333,
        127.1333333333,
        127.1333333333,
        127.1333333335,
        228.6,
    ]
    sections = [11, 10, 10, 10, 10, 10, 10, 11]
    for element_tag in range(1, levels + 1):
        bottom_left = 2 * element_tag - 1
        bottom_right = 2 * element_tag
        top_left = bottom_left + 2
        top_right = bottom_right + 2
        width_text = ", ".join(repr(value) for value in widths)
        section_text = ", ".join(str(value) for value in sections)
        lines.append(
            f"ops.element('MEFI', {element_tag}, "
            f"{bottom_left}, {bottom_right}, {top_right}, {top_left}, 8, "
            f"'-width', {width_text}, '-sec', {section_text})"
        )

    imported = import_openseespy_source(
        "\n".join(lines),
        source_name="imported-rw-a20.py",
        units={"length": "mm", "force": "N", "time": "s"},
    )
    assert imported.error_count == 0
    assert imported.unsupported_count == 0

    project = imported.project
    time_series = {
        1: TimeSeriesData(1, "Lateral", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(
            1,
            "Lateral",
            "Plain",
            time_series_tag=1,
        )
    }
    loads = {
        1: NodalLoadData(
            1,
            "Top left",
            pattern_tag=1,
            node_tag=15,
            values=(50000.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        ),
        2: NodalLoadData(
            2,
            "Top right",
            pattern_tag=1,
            node_tag=16,
            values=(50000.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        ),
    }
    analysis = AnalysisSettingsData(
        1,
        "Imported RC wall crack check",
        analysis_type="Static",
        constraints_handler="Transformation",
        numberer="RCM",
        system="UmfPack",
        test="NormDispIncr",
        tolerance=1.0e-8,
        max_iterations=100,
        algorithm="Newton",
        integrator="LoadControl",
        steps=100,
        load_increment=0.01,
        control_node=16,
        control_dof=1,
        recovery=True,
        adaptive_step=False,
        live_convergence=False,
    )

    script = to_openseespy(
        project.model,
        materials=project.materials,
        sections=project.sections,
        transformations=project.transformations,
        constraints=project.constraints,
        connections=project.connections,
        time_series=time_series,
        load_patterns=patterns,
        nodal_loads=loads,
        analyses={1: analysis},
        active_analysis_tag=1,
        nd_materials=project.nd_materials,
        units=project.units,
    )

    script_path = tmp_path / "imported-rw-a20.py"
    result_path = tmp_path / "imported-rw-a20-result.json"
    script_path.write_text(script, encoding="utf-8")
    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"
    results = payload["results"]

    states = mefi_crack_panel_states(results)
    summary = mefi_crack_summary(states)
    assert summary["elements"] == 7
    assert summary["panels"] == 56
    assert summary["valid_panels"] == 56
    assert summary["cracked"] >= 1
    assert summary["max_ratio"] >= 1.0
    assert len(results["history"]["mefi_panel_strains"]["1"]["1"]) == 100
