from __future__ import annotations

import importlib.util
import json
from pathlib import Path
import subprocess
import sys

import pytest

from openseespy_studio.generator import material_to_openseespy, to_openseespy
from openseespy_studio.importer import import_openseespy_source
from openseespy_studio.model import StructuralModel
from openseespy_studio.project import (
    MATERIAL_DEFAULTS,
    AnalysisSettingsData,
    ConnectionData,
    FiberData,
    LoadPatternData,
    MaterialData,
    NodalLoadData,
    RecorderData,
    SectionData,
    SolutionResultData,
    TimeSeriesData,
    TransformationData,
)
from openseespy_studio.solver_worker import run_script
from openseespy_studio.ui.viewport import ModelViewport


pytestmark = pytest.mark.integration

if importlib.util.find_spec("openseespy") is None:
    pytest.skip(
        "OpenSeesPy runtime is not installed in the unit-test environment.",
        allow_module_level=True,
    )


def test_generated_static_cantilever_runs_in_real_opensees(tmp_path: Path):
    model = StructuralModel("real-opensees-smoke")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 0.0, 0.0, 3.0)
    model.set_fixity(1, (1, 1, 1, 1, 1, 1))
    model.add_element(
        1,
        1,
        2,
        section_tag=1,
        transf_tag=1,
    )

    sections = {
        1: SectionData(
            1,
            "Elastic column",
            "Elastic",
            parameters={
                "E": 200.0e9,
                "A": 0.02,
                "Iz": 8.0e-5,
                "Iy": 8.0e-5,
                "G": 80.0e9,
                "J": 1.0e-4,
            },
        )
    }
    transformations = {
        1: TransformationData(
            1,
            "Column",
            "Linear",
            (1.0, 0.0, 0.0),
        )
    }
    time_series = {
        1: TimeSeriesData(1, "Linear", "Linear", factor=1.0)
    }
    load_patterns = {
        1: LoadPatternData(
            1,
            "Lateral",
            "Plain",
            time_series_tag=1,
        )
    }
    nodal_loads = {
        1: NodalLoadData(
            1,
            "Top lateral",
            pattern_tag=1,
            node_tag=2,
            values=(1000.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "Static smoke",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-12,
        max_iterations=20,
        algorithm="Newton",
        steps=1,
        load_increment=1.0,
        control_node=2,
        control_dof=1,
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    script = to_openseespy(
        model,
        sections=sections,
        transformations=transformations,
        time_series=time_series,
        load_patterns=load_patterns,
        nodal_loads=nodal_loads,
        analyses={1: analysis},
        active_analysis_tag=1,
        units={"length": "m", "force": "N", "time": "s"},
    )
    assert "# ERROR:" not in script

    script_path = tmp_path / "cantilever.py"
    result_path = tmp_path / "cantilever-result.json"
    script_path.write_text(script, encoding="utf-8")

    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0
    assert payload["status"] == "completed"
    results = payload["results"]
    assert results["analysis"]["type"] == "Static"
    assert results["convergence"]["steps"][0]["status"] in {
        "converged",
        "recovered",
    }

    displacement = results["final"]["node_displacements"]["2"][0]
    expected = 1000.0 * 3.0**3 / (
        3.0 * 200.0e9 * 8.0e-5
    )
    assert displacement == pytest.approx(expected, rel=1.0e-6)

    reaction = results["final"]["node_reactions"]["1"][0]
    assert reaction == pytest.approx(-1000.0, rel=1.0e-8)

    # The exported source must also run as an ordinary Python script,
    # without the Studio worker or any openseespy_studio import.
    assert "import openseespy_studio" not in script
    standalone = subprocess.run(
        [sys.executable, str(script_path)],
        cwd=tmp_path,
        text=True,
        capture_output=True,
        check=False,
        timeout=30,
    )
    assert standalone.returncode == 0, standalone.stderr
    assert "Model generated by OpenSeesPy Studio" in standalone.stdout


def _elastic_cantilever(*, mass: float = 0.0):
    model = StructuralModel("real-opensees-workflow")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 0.0, 0.0, 3.0)
    model.set_fixity(1, (1, 1, 1, 1, 1, 1))
    if mass > 0.0:
        model.set_mass(
            2,
            (mass, mass, mass, 0.0, 0.0, 0.0),
        )
    model.add_element(
        1,
        1,
        2,
        section_tag=1,
        transf_tag=1,
    )
    sections = {
        1: SectionData(
            1,
            "Elastic column",
            "Elastic",
            parameters={
                "E": 200.0e9,
                "A": 0.02,
                "Iz": 8.0e-5,
                "Iy": 8.0e-5,
                "G": 80.0e9,
                "J": 1.0e-4,
            },
        )
    }
    transformations = {
        1: TransformationData(
            1,
            "Column",
            "Linear",
            (1.0, 0.0, 0.0),
        )
    }
    return model, sections, transformations


def _run_real_generated(
    tmp_path: Path,
    name: str,
    *,
    model: StructuralModel,
    sections: dict[int, SectionData],
    transformations: dict[int, TransformationData],
    analysis: AnalysisSettingsData,
    materials: dict[int, MaterialData] | None = None,
    connections: dict[int, ConnectionData] | None = None,
    time_series: dict[int, TimeSeriesData] | None = None,
    load_patterns: dict[int, LoadPatternData] | None = None,
    nodal_loads: dict[int, NodalLoadData] | None = None,
):
    script = to_openseespy(
        model,
        materials=materials,
        sections=sections,
        transformations=transformations,
        connections=connections,
        time_series=time_series,
        load_patterns=load_patterns,
        nodal_loads=nodal_loads,
        analyses={analysis.tag: analysis},
        active_analysis_tag=analysis.tag,
        units={"length": "m", "force": "N", "time": "s"},
    )
    assert "# ERROR:" not in script
    assert "import openseespy_studio" not in script
    compile(script, f"<{name}>", "exec")

    script_path = tmp_path / f"{name}.py"
    result_path = tmp_path / f"{name}-result.json"
    script_path.write_text(script, encoding="utf-8")
    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"
    return payload["results"]


def test_frp_confined_concrete_material_constructs_in_real_opensees(
    tmp_path: Path,
):
    material = MaterialData(
        77,
        "FRP confined concrete",
        "FRPConfinedConcrete",
        parameters={
            "fpc1": 27.5e6,
            "fpc2": 27.5e6,
            "epsc0": 0.002,
            "D": 0.400,
            "c": 0.035,
            "Ej": 266.0e9,
            "Sj": 0.0,
            "tj": 0.000222,
            "eju": 0.0163,
            "S": 0.150,
            "fyl": 374.0e6,
            "fyh": 363.0e6,
            "dlong": 0.016,
            "dtrans": 0.006,
            "Es": 200.0e9,
            "nu0": 0.2,
            "k": 0.8,
            "useBuck": 1.0,
        },
    )
    material_line = material_to_openseespy(
        material,
        {"length": "mm", "force": "N", "time": "s"},
    )
    script = "\n".join([
        "import openseespy.opensees as ops",
        "ops.wipe()",
        "ops.model('basic', '-ndm', 1, '-ndf', 1)",
        material_line,
        "ops.node(1, 0.0)",
        "ops.node(2, 1.0)",
        "ops.fix(1, 1)",
        "ops.element('truss', 1, 1, 2, 1.0, 77)",
        "print('FRP_MATERIAL_OK')",
    ])
    script_path = tmp_path / "frp-material-smoke.py"
    script_path.write_text(script, encoding="utf-8")
    completed = subprocess.run(
        [sys.executable, str(script_path)],
        cwd=tmp_path,
        text=True,
        capture_output=True,
        check=False,
        timeout=30,
    )
    if (
        completed.returncode != 0
        and "temporarily removed from the compiled versions"
        in completed.stderr
    ):
        pytest.xfail(
            "Stock OpenSeesPy runtime omits legacy FRPConfinedConcrete."
        )
    assert completed.returncode == 0, completed.stderr
    assert "FRP_MATERIAL_OK" in completed.stdout


def test_imported_wfsection2d_conversion_runs_in_real_opensees(
    tmp_path: Path,
):
    source = r"""
from openseespy.opensees import *
wipe()
model('basic', '-ndm', 2, '-ndf', 3)
uniaxialMaterial(
    'Steel02', 1, 60.0, 29000.0, 0.10,
    18.0, 0.925, 0.15, 0.05, 1.0, 0.05, 1.0, 0.0
)
section('WFSection2d', 1, 1, 10.5, 0.26, 5.77, 0.44, 15, 16)
node(1, 0.0, 0.0)
node(2, 0.0, 120.0)
fix(1, 1, 1, 1)
geomTransf('PDelta', 1)
beamIntegration('Lobatto', 1, 1, 4)
element('forceBeamColumn', 1, 1, 2, 1, 1)
timeSeries('Linear', 1)
pattern('Plain', 1, 1)
load(2, 1.0, 0.0, 0.0)
system('BandGeneral')
numberer('Plain')
constraints('Plain')
test('NormUnbalance', 1.0e-10, 30)
algorithm('Newton')
integrator('LoadControl', 1.0)
analysis('Static')
analyze(1)
"""
    imported = import_openseespy_source(
        source,
        source_name="wf-real-smoke.py",
        units={"length": "in", "force": "kip", "time": "s"},
    )
    assert imported.error_count == 0
    assert imported.project.sections[1].section_type == "Fiber"
    assert len(imported.project.sections[1].compiled_fibers()) == 47

    project = imported.project
    script = to_openseespy(
        project.model,
        materials=project.materials,
        sections=project.sections,
        transformations=project.transformations,
        constraints=project.constraints,
        connections=project.connections,
        time_series=project.time_series,
        load_patterns=project.load_patterns,
        nodal_loads=project.nodal_loads,
        analyses=project.analyses,
        active_analysis_tag=project.active_analysis_tag,
        recorders=project.recorders,
        units=project.units,
    )
    assert "WFSection2d" not in script
    assert "ops.patch('rect'" in script
    assert "# ERROR:" not in script

    script_path = tmp_path / "wf-converted.py"
    result_path = tmp_path / "wf-converted-result.json"
    script_path.write_text(script, encoding="utf-8")
    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"
    assert payload["results"]["analysis"]["type"] == "Static"
    displacement = payload["results"]["final"]["node_displacements"]["2"][0]
    assert displacement > 0.0


def test_generated_2d_elastic_frame_with_linear_algorithm_runs(
    tmp_path: Path,
):
    model = StructuralModel("real-2d-frame", ndm=2, ndf=3)
    model.add_node(1, 0.0, 0.0)
    model.add_node(2, 0.0, 3.0)
    model.set_fixity(1, (1, 1, 1))
    model.add_element(
        1,
        1,
        2,
        element_type="elasticBeamColumn",
        section_tag=1,
        transf_tag=1,
    )
    sections = {
        1: SectionData(
            1,
            "2D elastic section",
            "Elastic",
            parameters={
                "E": 200.0e9,
                "A": 0.02,
                "Iz": 8.0e-5,
                "Iy": 0.0,
                "G": 0.0,
                "J": 0.0,
            },
        )
    }
    transformations = {
        1: TransformationData(1, "2D Linear", "Linear")
    }
    series = {
        1: TimeSeriesData(1, "Load", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Lateral", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Top load",
            pattern_tag=1,
            node_tag=2,
            values=(1000.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "2D linear static",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        algorithm="Linear",
        integrator="LoadControl",
        steps=1,
        load_increment=1.0,
        control_node=2,
        control_dof=1,
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    script = to_openseespy(
        model,
        sections=sections,
        transformations=transformations,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
        analyses={1: analysis},
        active_analysis_tag=1,
        units={"length": "m", "force": "N", "time": "s"},
    )
    assert "ops.model('basic', '-ndm', 2, '-ndf', 3)" in script
    assert "ops.section('Elastic', 1, 2e+11, 0.02, 8e-05)" in script
    assert "ops.geomTransf('Linear', 1)" in script
    assert (
        "ops.element('elasticBeamColumn', 1, 1, 2, "
        "0.02, 2e+11, 8e-05, 1)"
    ) in script
    assert "_studio_primary_algorithm = 'Linear'" in script
    assert "ops.test(" not in script

    script_path = tmp_path / "frame2d-linear.py"
    result_path = tmp_path / "frame2d-linear-result.json"
    script_path.write_text(script, encoding="utf-8")
    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"
    displacement = payload["results"]["final"]["node_displacements"]["2"][0]
    expected = 1000.0 * 3.0**3 / (
        3.0 * 200.0e9 * 8.0e-5
    )
    assert displacement == pytest.approx(expected, rel=1.0e-6)


def test_modified_newton_initial_runs_in_real_opensees(tmp_path: Path):
    model, sections, transformations = _elastic_cantilever()
    series = {
        1: TimeSeriesData(1, "Load", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Lateral", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Top load",
            pattern_tag=1,
            node_tag=2,
            values=(1000.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        91,
        "ModifiedNewton initial smoke",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-10,
        max_iterations=20,
        algorithm="ModifiedNewton",
        algorithm_initial=True,
        integrator="LoadControl",
        steps=1,
        load_increment=1.0,
        control_node=2,
        control_dof=1,
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    script = to_openseespy(
        model,
        sections=sections,
        transformations=transformations,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
        analyses={91: analysis},
        active_analysis_tag=91,
        units={"length": "m", "force": "N", "time": "s"},
    )
    assert "ops.algorithm('ModifiedNewton', '-initial')" in script

    script_path = tmp_path / "modified-newton-initial.py"
    result_path = tmp_path / "modified-newton-initial-result.json"
    script_path.write_text(script, encoding="utf-8")
    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"
    assert payload["results"]["analysis"]["algorithm_initial"] is True


def test_generated_moment_curvature_runs_in_real_opensees(tmp_path: Path):
    model = StructuralModel("moment-curvature-real", ndm=2, ndf=3)
    model.add_node(1, 0.0, 0.0)
    model.add_node(2, 0.0, 0.0)
    model.set_fixity(1, (1, 1, 1))
    model.set_fixity(2, (0, 1, 0))

    materials = {
        1: MaterialData(
            1,
            "Elastic section material",
            "Elastic",
            parameters={"E": 1000.0},
        )
    }
    sections = {
        1: SectionData(
            1,
            "Moment-curvature fiber section",
            "Fiber",
            fibers=[
                FiberData(-1.0, 0.0, 1.0, 1),
                FiberData(1.0, 0.0, 1.0, 1),
            ],
        )
    }
    connections = {
        1: ConnectionData(
            1,
            "Section test",
            "zeroLengthSection",
            1,
            2,
            section_tag=1,
        )
    }
    series = {
        1: TimeSeriesData(1, "Axial preload", "Constant", factor=1.0),
        2: TimeSeriesData(2, "Unit moment", "Linear", factor=1.0),
    }
    patterns = {
        1: LoadPatternData(1, "Axial preload", "Plain", time_series_tag=1),
        2: LoadPatternData(2, "Moment driver", "Plain", time_series_tag=2),
    }
    loads = {
        1: NodalLoadData(
            1,
            "Axial preload",
            pattern_tag=1,
            node_tag=2,
            values=(-10.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        ),
        2: NodalLoadData(
            2,
            "Unit moment",
            pattern_tag=2,
            node_tag=2,
            values=(0.0, 0.0, 1.0, 0.0, 0.0, 0.0),
        ),
    }
    analysis = AnalysisSettingsData(
        1,
        "Moment-curvature smoke",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormUnbalance",
        tolerance=1.0e-10,
        max_iterations=20,
        algorithm="Newton",
        integrator="DisplacementControl",
        steps=4,
        control_node=2,
        control_dof=3,
        displacement_increment=0.001,
        preload_gravity=True,
        gravity_steps=1,
        deferred_pattern_tags=[2],
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    results = _run_real_generated(
        tmp_path,
        "moment-curvature",
        model=model,
        materials=materials,
        sections=sections,
        transformations={},
        connections=connections,
        analysis=analysis,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
    )

    spec = results["moment_curvature"]
    assert spec["kind"] == "moment-curvature"
    assert spec["element_tag"] == 1
    assert spec["moment_component"] == "Mz"
    assert spec["moment_index"] == 1

    history = results["history"]["moment_curvature"]
    assert len(history["force"]) == 4
    assert len(history["deformation"]) == 4
    curvature = [float(row[1]) for row in history["deformation"]]
    moment = [float(row[1]) for row in history["force"]]
    assert curvature[-1] == pytest.approx(0.004, abs=1.0e-10)
    assert abs(moment[-1]) > 0.0
    assert all(
        abs(curvature[index]) > abs(curvature[index - 1])
        for index in range(1, len(curvature))
    )


def test_generated_modal_runs_in_real_opensees(tmp_path: Path):
    model, sections, transformations = _elastic_cantilever(mass=1000.0)
    analysis = AnalysisSettingsData(
        1,
        "Modal smoke",
        analysis_type="Modal",
        num_modes=1,
        eigen_solver="-fullGenLapack",
        live_convergence=False,
    )

    results = _run_real_generated(
        tmp_path,
        "modal",
        model=model,
        sections=sections,
        transformations=transformations,
        analysis=analysis,
    )

    assert results["analysis"]["type"] == "Modal"
    assert len(results["eigenvalues"]) == 1
    assert float(results["eigenvalues"][0]) > 0.0
    assert "1" in results["modes"]


def test_generated_pushover_runs_in_real_opensees(tmp_path: Path):
    model, sections, transformations = _elastic_cantilever()
    series = {
        1: TimeSeriesData(1, "Push", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Push", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Reference lateral load",
            pattern_tag=1,
            node_tag=2,
            values=(1.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "Pushover smoke",
        analysis_type="Pushover",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-10,
        max_iterations=20,
        algorithm="Newton",
        steps=4,
        control_node=2,
        control_dof=1,
        displacement_increment=0.001,
        deferred_pattern_tags=[1],
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    results = _run_real_generated(
        tmp_path,
        "pushover",
        model=model,
        sections=sections,
        transformations=transformations,
        analysis=analysis,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
    )

    assert results["analysis"]["type"] == "Pushover"
    history = results["history"]["displacement"]
    assert len(history) == 4
    assert history[-1][0] == pytest.approx(0.004, abs=1.0e-10)
    assert abs(results["history"]["base_shear"][-1]) > 0.0


def test_generated_cyclic_runs_in_real_opensees(tmp_path: Path):
    model, sections, transformations = _elastic_cantilever()
    series = {
        1: TimeSeriesData(1, "Cyclic", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Cyclic", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Reference lateral load",
            pattern_tag=1,
            node_tag=2,
            values=(1.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "Cyclic smoke",
        analysis_type="Cyclic",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-10,
        max_iterations=20,
        algorithm="Newton",
        control_node=2,
        control_dof=1,
        cyclic_targets=[0.001, -0.001, 0.0],
        cyclic_increment=0.0005,
        deferred_pattern_tags=[1],
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    results = _run_real_generated(
        tmp_path,
        "cyclic",
        model=model,
        sections=sections,
        transformations=transformations,
        analysis=analysis,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
    )

    assert results["analysis"]["type"] == "Cyclic"
    displacement = [
        float(row[0])
        for row in results["history"]["displacement"]
    ]
    assert max(displacement) == pytest.approx(0.001, abs=1.0e-10)
    assert min(displacement) == pytest.approx(-0.001, abs=1.0e-10)
    assert displacement[-1] == pytest.approx(0.0, abs=1.0e-10)


def test_generated_nlth_runs_in_real_opensees(tmp_path: Path):
    model, sections, transformations = _elastic_cantilever(mass=1000.0)
    series = {
        1: TimeSeriesData(
            1,
            "Small ground motion",
            "Path",
            factor=1.0,
            dt=0.01,
            values=[0.0, 0.05, -0.05, 0.0],
        )
    }
    patterns = {
        1: LoadPatternData(
            1,
            "Ground motion X",
            "UniformExcitation",
            time_series_tag=1,
            direction=1,
            factor=1.0,
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "NLTH smoke",
        analysis_type="Transient",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-10,
        max_iterations=20,
        algorithm="Newton",
        steps=3,
        dt=0.01,
        control_node=2,
        control_dof=1,
        deferred_pattern_tags=[1],
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    results = _run_real_generated(
        tmp_path,
        "nlth",
        model=model,
        sections=sections,
        transformations=transformations,
        analysis=analysis,
        time_series=series,
        load_patterns=patterns,
    )

    assert results["analysis"]["type"] == "Transient"
    assert len(results["history"]["time"]) == 3
    assert results["history"]["time"][-1] == pytest.approx(0.03)
    node_history = results["history"]["nodes"]["2"]
    assert len(node_history["disp"]) == 3
    assert len(node_history["accel"]) == 3


def test_generated_fiber_force_beam_column_and_recorder_run_in_real_opensees(
    tmp_path: Path,
):
    model = StructuralModel("fiber-export-smoke")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 0.0, 0.0, 3.0)
    model.set_fixity(1, (1, 1, 1, 1, 1, 1))
    model.add_element(
        1,
        1,
        2,
        element_type="forceBeamColumn",
        section_tag=1,
        transf_tag=1,
        integration_type="Lobatto",
        integration_points=3,
    )

    materials = {
        1: MaterialData(
            1,
            "Elastic fiber",
            "Elastic",
            parameters={"E": 200.0e9},
        )
    }
    sections = {
        1: SectionData(
            1,
            "Fiber section",
            "Fiber",
            parameters={"GJ": 1.0e6},
            fibers=[
                FiberData(-0.10, -0.10, 0.005, 1),
                FiberData(-0.10, 0.10, 0.005, 1),
                FiberData(0.10, -0.10, 0.005, 1),
                FiberData(0.10, 0.10, 0.005, 1),
            ],
        )
    }
    transformations = {
        1: TransformationData(
            1,
            "Column",
            "Linear",
            (1.0, 0.0, 0.0),
        )
    }
    series = {
        1: TimeSeriesData(1, "Axial", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Axial", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Top axial",
            pattern_tag=1,
            node_tag=2,
            values=(0.0, 0.0, -1000.0, 0.0, 0.0, 0.0),
        )
    }
    recorder_path = tmp_path / "fiber-node-disp.out"
    recorders = {
        1: RecorderData(
            1,
            "Top UZ",
            "Node",
            target_tags=[2],
            response="disp",
            dofs=[3],
            file_name=str(recorder_path),
            include_time=True,
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "Fiber static",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-10,
        max_iterations=20,
        algorithm="Newton",
        steps=1,
        load_increment=1.0,
        control_node=2,
        control_dof=3,
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )
    section_response = SolutionResultData(
        2,
        1,
        "Axial section response",
        "SectionResponse",
        element_scope=[1],
        settings={"section": 1, "component": "P"},
    )

    script = to_openseespy(
        model,
        materials=materials,
        sections=sections,
        transformations=transformations,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
        analyses={1: analysis},
        active_analysis_tag=1,
        recorders=recorders,
        units={"length": "m", "force": "N", "time": "s"},
        solution_results={2: section_response},
    )
    assert "# ERROR:" not in script
    compile(script, "<fiber-export>", "exec")

    script_path = tmp_path / "fiber-export.py"
    result_path = tmp_path / "fiber-export-result.json"
    script_path.write_text(script, encoding="utf-8")
    assert run_script(script_path, result_path) == 0

    payload = json.loads(result_path.read_text(encoding="utf-8"))
    assert payload["status"] == "completed"
    assert payload["results"]["analysis"]["type"] == "Static"
    assert payload["results"]["final"]["node_displacements"]["2"][2] < 0.0
    generic = payload["results"]["history"]["section_responses"]["request:2"]
    assert len(generic["force"]) == 1
    assert len(generic["deformation"]) == 1
    assert abs(float(generic["force"][0][0])) > 0.0
    assert abs(float(generic["deformation"][0][0])) > 0.0
    assert recorder_path.exists()
    assert recorder_path.read_text(encoding="utf-8").strip()


def test_generated_zero_length_spring_runs_in_real_opensees(tmp_path: Path):
    model = StructuralModel("zero-length-export-smoke")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 0.0, 0.0, 0.0)
    model.set_fixity(1, (1, 1, 1, 1, 1, 1))
    model.set_fixity(2, (0, 1, 1, 1, 1, 1))

    materials = {
        1: MaterialData(
            1,
            "Translation spring",
            "Elastic",
            parameters={"E": 1.0e6},
        )
    }
    connections = {
        10: ConnectionData(
            10,
            "Base spring",
            "zeroLength",
            1,
            2,
            materials_by_dof={1: 1},
        )
    }
    series = {
        1: TimeSeriesData(1, "Load", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Load", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Spring load",
            pattern_tag=1,
            node_tag=2,
            values=(1000.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "Spring static",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-12,
        max_iterations=20,
        algorithm="Newton",
        steps=1,
        load_increment=1.0,
        control_node=2,
        control_dof=1,
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    script = to_openseespy(
        model,
        materials=materials,
        connections=connections,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
        analyses={1: analysis},
        active_analysis_tag=1,
        units={"length": "m", "force": "N", "time": "s"},
    )
    assert "# ERROR:" not in script
    compile(script, "<zero-length-export>", "exec")

    script_path = tmp_path / "zero-length-export.py"
    result_path = tmp_path / "zero-length-export-result.json"
    script_path.write_text(script, encoding="utf-8")
    assert run_script(script_path, result_path) == 0

    payload = json.loads(result_path.read_text(encoding="utf-8"))
    assert payload["status"] == "completed"
    displacement = payload["results"]["final"]["node_displacements"]["2"][0]
    assert displacement == pytest.approx(0.001, rel=1.0e-8)


def test_research_material_commands_load_in_real_opensees(tmp_path: Path):
    model = StructuralModel("research-material-export-smoke")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.set_fixity(1, (1, 1, 1, 1, 1, 1))

    materials = {
        1: MaterialData(
            1,
            "Bond",
            "Bond_SP01",
            parameters=MATERIAL_DEFAULTS["Bond_SP01"],
        ),
        2: MaterialData(
            2,
            "FRP jacket",
            "FRPConfinedConcrete02",
            parameters=MATERIAL_DEFAULTS["FRPConfinedConcrete02"],
        ),
        3: MaterialData(
            3,
            "Combined hardening",
            "Hardening",
            parameters=MATERIAL_DEFAULTS["Hardening"],
        ),
        4: MaterialData(
            4,
            "Elastic perfectly plastic",
            "ElasticPP",
            parameters=MATERIAL_DEFAULTS["ElasticPP"],
        ),
        5: MaterialData(
            5,
            "Elastic bilinear",
            "ElasticBilin",
            parameters=MATERIAL_DEFAULTS["ElasticBilin"],
        ),
        6: MaterialData(
            6,
            "Smooth hysteresis",
            "HystereticSmooth",
            parameters=MATERIAL_DEFAULTS["HystereticSmooth"],
        ),
    }

    script = to_openseespy(
        model,
        materials=materials,
        units={"length": "mm", "force": "N", "time": "s"},
    )
    assert "# ERROR:" not in script
    compile(script, "<research-material-export>", "exec")

    script_path = tmp_path / "research-material-export.py"
    result_path = tmp_path / "research-material-export-result.json"
    script_path.write_text(script, encoding="utf-8")
    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"


def test_batched_centerline_mesh_contains_only_line_cells():
    model = StructuralModel("centerline-smoke")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 4.0, 0.0, 0.0)
    model.add_node(3, 4.0, 0.0, 3.0)
    model.add_element(11, 1, 2)
    model.add_element(12, 2, 3)

    mesh = ModelViewport._batched_centerline_mesh(model, [11, 12])

    assert mesh is not None
    assert mesh.n_points == 4
    assert mesh.n_lines == 2
    assert mesh.n_verts == 0
    assert mesh.n_cells == 2
    assert list(mesh.cell_data["element_tag"]) == [11, 12]


def test_generated_truss_runs_and_captures_axial_force_in_real_opensees(
    tmp_path: Path,
):
    model = StructuralModel("truss-real-opensees")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 2.0, 0.0, 0.0)
    model.set_fixity(1, (1, 1, 1, 1, 1, 1))
    model.set_fixity(2, (0, 1, 1, 1, 1, 1))
    model.add_element(
        1,
        1,
        2,
        element_type="truss",
        group="truss",
        truss_area=0.01,
        truss_material_tag=1,
    )

    materials = {
        1: MaterialData(
            1,
            "Elastic truss steel",
            "Elastic",
            parameters={"E": 200.0e9},
        )
    }
    series = {
        1: TimeSeriesData(1, "Axial", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Axial", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Axial tension",
            pattern_tag=1,
            node_tag=2,
            values=(1000.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "Truss static",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-12,
        max_iterations=20,
        algorithm="Newton",
        steps=1,
        load_increment=1.0,
        control_node=2,
        control_dof=1,
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    script = to_openseespy(
        model,
        materials=materials,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
        analyses={1: analysis},
        active_analysis_tag=1,
        units={"length": "m", "force": "N", "time": "s"},
    )
    assert "# ERROR:" not in script
    assert "ops.element('Truss', 1, 1, 2, 0.01, 1)" in script
    assert "'element_axial_forces': _studio_element_axial_forces" in script

    script_path = tmp_path / "truss-static.py"
    result_path = tmp_path / "truss-static-result.json"
    script_path.write_text(script, encoding="utf-8")

    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"

    results = payload["results"]
    displacement = results["final"]["node_displacements"]["2"][0]
    assert displacement == pytest.approx(1.0e-6, rel=1.0e-6)

    axial_force = results["final"]["element_axial_forces"]["1"]
    assert abs(float(axial_force)) == pytest.approx(1000.0, rel=1.0e-8)

    global_force = results["final"]["element_forces"]["1"]
    assert len(global_force) >= 6
    assert max(abs(float(value)) for value in global_force) == pytest.approx(
        1000.0,
        rel=1.0e-8,
    )


def test_generated_2d_2dof_truss_runs_and_reports_axial_force(
    tmp_path: Path,
):
    model = StructuralModel("truss-2d-2dof", ndm=2, ndf=2)
    model.add_node(1, 0.0, 0.0)
    model.add_node(2, 2.0, 0.0)
    model.set_fixity(1, (1, 1))
    model.set_fixity(2, (0, 1))
    model.add_element(
        1,
        1,
        2,
        element_type="truss",
        group="truss",
        truss_area=0.01,
        truss_material_tag=1,
    )

    materials = {
        1: MaterialData(
            1,
            "Elastic truss steel",
            "Elastic",
            parameters={"E": 200.0e9},
        )
    }
    series = {
        1: TimeSeriesData(1, "Axial", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Axial", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Axial tension",
            pattern_tag=1,
            node_tag=2,
            values=(1000.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "2D Truss static",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-12,
        max_iterations=20,
        algorithm="Newton",
        steps=1,
        load_increment=1.0,
        control_node=2,
        control_dof=1,
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    script = to_openseespy(
        model,
        materials=materials,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
        analyses={1: analysis},
        active_analysis_tag=1,
        units={"length": "m", "force": "N", "time": "s"},
    )

    assert "ops.model('basic', '-ndm', 2, '-ndf', 2)" in script
    assert "ops.node(1, 0, 0)" in script
    assert "ops.node(2, 2, 0)" in script
    assert "ops.fix(1, 1, 1)" in script
    assert "ops.fix(2, 0, 1)" in script
    assert "ops.load(2, 1000, 0)" in script
    assert "# ERROR:" not in script

    script_path = tmp_path / "truss-2d.py"
    result_path = tmp_path / "truss-2d-result.json"
    script_path.write_text(script, encoding="utf-8")

    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"
    results = payload["results"]
    assert results["final"]["node_displacements"]["2"][0] == pytest.approx(
        1.0e-6,
        rel=1.0e-6,
    )
    axial = results["final"]["element_axial_forces"]["1"]
    assert abs(float(axial)) == pytest.approx(1000.0, rel=1.0e-8)
