from __future__ import annotations

import importlib.util
import json
from pathlib import Path
import subprocess
import sys

import pytest

from openseespy_studio.generator import to_openseespy
from openseespy_studio.model import StructuralModel
from openseespy_studio.project import (
    MATERIAL_DEFAULTS,
    AnalysisSettingsData,
    ConnectionData,
    FiberData,
    LoadPatternData,
    MaterialData,
    NodalLoadData,
    RecorderData,
    SectionData,
    TimeSeriesData,
    TransformationData,
)
from openseespy_studio.solver_worker import run_script
from openseespy_studio.ui.viewport import ModelViewport


pytestmark = pytest.mark.integration

if importlib.util.find_spec("openseespy") is None:
    pytest.skip(
        "OpenSeesPy runtime is not installed in the unit-test environment.",
        allow_module_level=True,
    )


def test_generated_static_cantilever_runs_in_real_opensees(tmp_path: Path):
    model = StructuralModel("real-opensees-smoke")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 0.0, 0.0, 3.0)
    model.set_fixity(1, (1, 1, 1, 1, 1, 1))
    model.add_element(
        1,
        1,
        2,
        section_tag=1,
        transf_tag=1,
    )

    sections = {
        1: SectionData(
            1,
            "Elastic column",
            "Elastic",
            parameters={
                "E": 200.0e9,
                "A": 0.02,
                "Iz": 8.0e-5,
                "Iy": 8.0e-5,
                "G": 80.0e9,
                "J": 1.0e-4,
            },
        )
    }
    transformations = {
        1: TransformationData(
            1,
            "Column",
            "Linear",
            (1.0, 0.0, 0.0),
        )
    }
    time_series = {
        1: TimeSeriesData(1, "Linear", "Linear", factor=1.0)
    }
    load_patterns = {
        1: LoadPatternData(
            1,
            "Lateral",
            "Plain",
            time_series_tag=1,
        )
    }
    nodal_loads = {
        1: NodalLoadData(
            1,
            "Top lateral",
            pattern_tag=1,
            node_tag=2,
            values=(1000.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "Static smoke",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-12,
        max_iterations=20,
        algorithm="Newton",
        steps=1,
        load_increment=1.0,
        control_node=2,
        control_dof=1,
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    script = to_openseespy(
        model,
        sections=sections,
        transformations=transformations,
        time_series=time_series,
        load_patterns=load_patterns,
        nodal_loads=nodal_loads,
        analyses={1: analysis},
        active_analysis_tag=1,
        units={"length": "m", "force": "N", "time": "s"},
    )
    assert "# ERROR:" not in script

    script_path = tmp_path / "cantilever.py"
    result_path = tmp_path / "cantilever-result.json"
    script_path.write_text(script, encoding="utf-8")

    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0
    assert payload["status"] == "completed"
    results = payload["results"]
    assert results["analysis"]["type"] == "Static"
    assert results["convergence"]["steps"][0]["status"] in {
        "converged",
        "recovered",
    }

    displacement = results["final"]["node_displacements"]["2"][0]
    expected = 1000.0 * 3.0**3 / (
        3.0 * 200.0e9 * 8.0e-5
    )
    assert displacement == pytest.approx(expected, rel=1.0e-6)

    reaction = results["final"]["node_reactions"]["1"][0]
    assert reaction == pytest.approx(-1000.0, rel=1.0e-8)

    # The exported source must also run as an ordinary Python script,
    # without the Studio worker or any openseespy_studio import.
    assert "import openseespy_studio" not in script
    standalone = subprocess.run(
        [sys.executable, str(script_path)],
        cwd=tmp_path,
        text=True,
        capture_output=True,
        check=False,
        timeout=30,
    )
    assert standalone.returncode == 0, standalone.stderr
    assert "Model generated by OpenSeesPy Studio" in standalone.stdout


def _elastic_cantilever(*, mass: float = 0.0):
    model = StructuralModel("real-opensees-workflow")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 0.0, 0.0, 3.0)
    model.set_fixity(1, (1, 1, 1, 1, 1, 1))
    if mass > 0.0:
        model.set_mass(
            2,
            (mass, mass, mass, 0.0, 0.0, 0.0),
        )
    model.add_element(
        1,
        1,
        2,
        section_tag=1,
        transf_tag=1,
    )
    sections = {
        1: SectionData(
            1,
            "Elastic column",
            "Elastic",
            parameters={
                "E": 200.0e9,
                "A": 0.02,
                "Iz": 8.0e-5,
                "Iy": 8.0e-5,
                "G": 80.0e9,
                "J": 1.0e-4,
            },
        )
    }
    transformations = {
        1: TransformationData(
            1,
            "Column",
            "Linear",
            (1.0, 0.0, 0.0),
        )
    }
    return model, sections, transformations


def _run_real_generated(
    tmp_path: Path,
    name: str,
    *,
    model: StructuralModel,
    sections: dict[int, SectionData],
    transformations: dict[int, TransformationData],
    analysis: AnalysisSettingsData,
    time_series: dict[int, TimeSeriesData] | None = None,
    load_patterns: dict[int, LoadPatternData] | None = None,
    nodal_loads: dict[int, NodalLoadData] | None = None,
):
    script = to_openseespy(
        model,
        sections=sections,
        transformations=transformations,
        time_series=time_series,
        load_patterns=load_patterns,
        nodal_loads=nodal_loads,
        analyses={analysis.tag: analysis},
        active_analysis_tag=analysis.tag,
        units={"length": "m", "force": "N", "time": "s"},
    )
    assert "# ERROR:" not in script
    assert "import openseespy_studio" not in script
    compile(script, f"<{name}>", "exec")

    script_path = tmp_path / f"{name}.py"
    result_path = tmp_path / f"{name}-result.json"
    script_path.write_text(script, encoding="utf-8")
    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"
    return payload["results"]


def test_generated_modal_runs_in_real_opensees(tmp_path: Path):
    model, sections, transformations = _elastic_cantilever(mass=1000.0)
    analysis = AnalysisSettingsData(
        1,
        "Modal smoke",
        analysis_type="Modal",
        num_modes=1,
        eigen_solver="-fullGenLapack",
        live_convergence=False,
    )

    results = _run_real_generated(
        tmp_path,
        "modal",
        model=model,
        sections=sections,
        transformations=transformations,
        analysis=analysis,
    )

    assert results["analysis"]["type"] == "Modal"
    assert len(results["eigenvalues"]) == 1
    assert float(results["eigenvalues"][0]) > 0.0
    assert "1" in results["modes"]


def test_generated_pushover_runs_in_real_opensees(tmp_path: Path):
    model, sections, transformations = _elastic_cantilever()
    series = {
        1: TimeSeriesData(1, "Push", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Push", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Reference lateral load",
            pattern_tag=1,
            node_tag=2,
            values=(1.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "Pushover smoke",
        analysis_type="Pushover",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-10,
        max_iterations=20,
        algorithm="Newton",
        steps=4,
        control_node=2,
        control_dof=1,
        displacement_increment=0.001,
        deferred_pattern_tags=[1],
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    results = _run_real_generated(
        tmp_path,
        "pushover",
        model=model,
        sections=sections,
        transformations=transformations,
        analysis=analysis,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
    )

    assert results["analysis"]["type"] == "Pushover"
    history = results["history"]["displacement"]
    assert len(history) == 4
    assert history[-1][0] == pytest.approx(0.004, abs=1.0e-10)
    assert abs(results["history"]["base_shear"][-1]) > 0.0


def test_generated_cyclic_runs_in_real_opensees(tmp_path: Path):
    model, sections, transformations = _elastic_cantilever()
    series = {
        1: TimeSeriesData(1, "Cyclic", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Cyclic", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Reference lateral load",
            pattern_tag=1,
            node_tag=2,
            values=(1.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "Cyclic smoke",
        analysis_type="Cyclic",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-10,
        max_iterations=20,
        algorithm="Newton",
        control_node=2,
        control_dof=1,
        cyclic_targets=[0.001, -0.001, 0.0],
        cyclic_increment=0.0005,
        deferred_pattern_tags=[1],
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    results = _run_real_generated(
        tmp_path,
        "cyclic",
        model=model,
        sections=sections,
        transformations=transformations,
        analysis=analysis,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
    )

    assert results["analysis"]["type"] == "Cyclic"
    displacement = [
        float(row[0])
        for row in results["history"]["displacement"]
    ]
    assert max(displacement) == pytest.approx(0.001, abs=1.0e-10)
    assert min(displacement) == pytest.approx(-0.001, abs=1.0e-10)
    assert displacement[-1] == pytest.approx(0.0, abs=1.0e-10)


def test_generated_nlth_runs_in_real_opensees(tmp_path: Path):
    model, sections, transformations = _elastic_cantilever(mass=1000.0)
    series = {
        1: TimeSeriesData(
            1,
            "Small ground motion",
            "Path",
            factor=1.0,
            dt=0.01,
            values=[0.0, 0.05, -0.05, 0.0],
        )
    }
    patterns = {
        1: LoadPatternData(
            1,
            "Ground motion X",
            "UniformExcitation",
            time_series_tag=1,
            direction=1,
            factor=1.0,
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "NLTH smoke",
        analysis_type="Transient",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-10,
        max_iterations=20,
        algorithm="Newton",
        steps=3,
        dt=0.01,
        control_node=2,
        control_dof=1,
        deferred_pattern_tags=[1],
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    results = _run_real_generated(
        tmp_path,
        "nlth",
        model=model,
        sections=sections,
        transformations=transformations,
        analysis=analysis,
        time_series=series,
        load_patterns=patterns,
    )

    assert results["analysis"]["type"] == "Transient"
    assert len(results["history"]["time"]) == 3
    assert results["history"]["time"][-1] == pytest.approx(0.03)
    node_history = results["history"]["nodes"]["2"]
    assert len(node_history["disp"]) == 3
    assert len(node_history["accel"]) == 3


def test_generated_fiber_force_beam_column_and_recorder_run_in_real_opensees(
    tmp_path: Path,
):
    model = StructuralModel("fiber-export-smoke")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 0.0, 0.0, 3.0)
    model.set_fixity(1, (1, 1, 1, 1, 1, 1))
    model.add_element(
        1,
        1,
        2,
        element_type="forceBeamColumn",
        section_tag=1,
        transf_tag=1,
        integration_type="Lobatto",
        integration_points=3,
    )

    materials = {
        1: MaterialData(
            1,
            "Elastic fiber",
            "Elastic",
            parameters={"E": 200.0e9},
        )
    }
    sections = {
        1: SectionData(
            1,
            "Fiber section",
            "Fiber",
            parameters={"GJ": 1.0e6},
            fibers=[
                FiberData(-0.10, -0.10, 0.005, 1),
                FiberData(-0.10, 0.10, 0.005, 1),
                FiberData(0.10, -0.10, 0.005, 1),
                FiberData(0.10, 0.10, 0.005, 1),
            ],
        )
    }
    transformations = {
        1: TransformationData(
            1,
            "Column",
            "Linear",
            (1.0, 0.0, 0.0),
        )
    }
    series = {
        1: TimeSeriesData(1, "Axial", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Axial", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Top axial",
            pattern_tag=1,
            node_tag=2,
            values=(0.0, 0.0, -1000.0, 0.0, 0.0, 0.0),
        )
    }
    recorder_path = tmp_path / "fiber-node-disp.out"
    recorders = {
        1: RecorderData(
            1,
            "Top UZ",
            "Node",
            target_tags=[2],
            response="disp",
            dofs=[3],
            file_name=str(recorder_path),
            include_time=True,
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "Fiber static",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-10,
        max_iterations=20,
        algorithm="Newton",
        steps=1,
        load_increment=1.0,
        control_node=2,
        control_dof=3,
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    script = to_openseespy(
        model,
        materials=materials,
        sections=sections,
        transformations=transformations,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
        analyses={1: analysis},
        active_analysis_tag=1,
        recorders=recorders,
        units={"length": "m", "force": "N", "time": "s"},
    )
    assert "# ERROR:" not in script
    compile(script, "<fiber-export>", "exec")

    script_path = tmp_path / "fiber-export.py"
    result_path = tmp_path / "fiber-export-result.json"
    script_path.write_text(script, encoding="utf-8")
    assert run_script(script_path, result_path) == 0

    payload = json.loads(result_path.read_text(encoding="utf-8"))
    assert payload["status"] == "completed"
    assert payload["results"]["analysis"]["type"] == "Static"
    assert payload["results"]["final"]["node_displacements"]["2"][2] < 0.0
    assert recorder_path.exists()
    assert recorder_path.read_text(encoding="utf-8").strip()


def test_generated_zero_length_spring_runs_in_real_opensees(tmp_path: Path):
    model = StructuralModel("zero-length-export-smoke")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 0.0, 0.0, 0.0)
    model.set_fixity(1, (1, 1, 1, 1, 1, 1))
    model.set_fixity(2, (0, 1, 1, 1, 1, 1))

    materials = {
        1: MaterialData(
            1,
            "Translation spring",
            "Elastic",
            parameters={"E": 1.0e6},
        )
    }
    connections = {
        10: ConnectionData(
            10,
            "Base spring",
            "zeroLength",
            1,
            2,
            materials_by_dof={1: 1},
        )
    }
    series = {
        1: TimeSeriesData(1, "Load", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Load", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Spring load",
            pattern_tag=1,
            node_tag=2,
            values=(1000.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "Spring static",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-12,
        max_iterations=20,
        algorithm="Newton",
        steps=1,
        load_increment=1.0,
        control_node=2,
        control_dof=1,
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    script = to_openseespy(
        model,
        materials=materials,
        connections=connections,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
        analyses={1: analysis},
        active_analysis_tag=1,
        units={"length": "m", "force": "N", "time": "s"},
    )
    assert "# ERROR:" not in script
    compile(script, "<zero-length-export>", "exec")

    script_path = tmp_path / "zero-length-export.py"
    result_path = tmp_path / "zero-length-export-result.json"
    script_path.write_text(script, encoding="utf-8")
    assert run_script(script_path, result_path) == 0

    payload = json.loads(result_path.read_text(encoding="utf-8"))
    assert payload["status"] == "completed"
    displacement = payload["results"]["final"]["node_displacements"]["2"][0]
    assert displacement == pytest.approx(0.001, rel=1.0e-8)


def test_research_material_commands_load_in_real_opensees(tmp_path: Path):
    model = StructuralModel("research-material-export-smoke")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.set_fixity(1, (1, 1, 1, 1, 1, 1))

    materials = {
        1: MaterialData(
            1,
            "Bond",
            "Bond_SP01",
            parameters=MATERIAL_DEFAULTS["Bond_SP01"],
        ),
        2: MaterialData(
            2,
            "FRP jacket",
            "FRPConfinedConcrete02",
            parameters=MATERIAL_DEFAULTS["FRPConfinedConcrete02"],
        ),
    }

    script = to_openseespy(
        model,
        materials=materials,
        units={"length": "mm", "force": "N", "time": "s"},
    )
    assert "# ERROR:" not in script
    compile(script, "<research-material-export>", "exec")

    script_path = tmp_path / "research-material-export.py"
    result_path = tmp_path / "research-material-export-result.json"
    script_path.write_text(script, encoding="utf-8")
    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"


def test_batched_centerline_mesh_contains_only_line_cells():
    model = StructuralModel("centerline-smoke")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 4.0, 0.0, 0.0)
    model.add_node(3, 4.0, 0.0, 3.0)
    model.add_element(11, 1, 2)
    model.add_element(12, 2, 3)

    mesh = ModelViewport._batched_centerline_mesh(model, [11, 12])

    assert mesh is not None
    assert mesh.n_points == 4
    assert mesh.n_lines == 2
    assert mesh.n_verts == 0
    assert mesh.n_cells == 2
    assert list(mesh.cell_data["element_tag"]) == [11, 12]


def test_generated_truss_runs_and_captures_axial_force_in_real_opensees(
    tmp_path: Path,
):
    model = StructuralModel("truss-real-opensees")
    model.add_node(1, 0.0, 0.0, 0.0)
    model.add_node(2, 2.0, 0.0, 0.0)
    model.set_fixity(1, (1, 1, 1, 1, 1, 1))
    model.set_fixity(2, (0, 1, 1, 1, 1, 1))
    model.add_element(
        1,
        1,
        2,
        element_type="truss",
        group="truss",
        truss_area=0.01,
        truss_material_tag=1,
    )

    materials = {
        1: MaterialData(
            1,
            "Elastic truss steel",
            "Elastic",
            parameters={"E": 200.0e9},
        )
    }
    series = {
        1: TimeSeriesData(1, "Axial", "Linear", factor=1.0)
    }
    patterns = {
        1: LoadPatternData(1, "Axial", "Plain", time_series_tag=1)
    }
    loads = {
        1: NodalLoadData(
            1,
            "Axial tension",
            pattern_tag=1,
            node_tag=2,
            values=(1000.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        )
    }
    analysis = AnalysisSettingsData(
        1,
        "Truss static",
        analysis_type="Static",
        constraints_handler="Plain",
        numberer="Plain",
        system="BandGeneral",
        test="NormDispIncr",
        tolerance=1.0e-12,
        max_iterations=20,
        algorithm="Newton",
        steps=1,
        load_increment=1.0,
        control_node=2,
        control_dof=1,
        recovery=False,
        adaptive_step=False,
        live_convergence=False,
    )

    script = to_openseespy(
        model,
        materials=materials,
        time_series=series,
        load_patterns=patterns,
        nodal_loads=loads,
        analyses={1: analysis},
        active_analysis_tag=1,
        units={"length": "m", "force": "N", "time": "s"},
    )
    assert "# ERROR:" not in script
    assert "ops.element('Truss', 1, 1, 2, 0.01, 1)" in script
    assert "'element_axial_forces': _studio_element_axial_forces" in script

    script_path = tmp_path / "truss-static.py"
    result_path = tmp_path / "truss-static-result.json"
    script_path.write_text(script, encoding="utf-8")

    exit_code = run_script(script_path, result_path)
    payload = json.loads(result_path.read_text(encoding="utf-8"))

    assert exit_code == 0, payload.get("error", "")
    assert payload["status"] == "completed"

    results = payload["results"]
    displacement = results["final"]["node_displacements"]["2"][0]
    assert displacement == pytest.approx(1.0e-6, rel=1.0e-6)

    axial_force = results["final"]["element_axial_forces"]["1"]
    assert abs(float(axial_force)) == pytest.approx(1000.0, rel=1.0e-8)

    global_force = results["final"]["element_forces"]["1"]
    assert len(global_force) >= 6
    assert max(abs(float(value)) for value in global_force) == pytest.approx(
        1000.0,
        rel=1.0e-8,
    )
